call bxl_main instead of bxl
Summary:
Rust analyzer restart command on VSCode is broken
```
[marwhal@devvm119.rva0 ~/fbsource/fbcode/buck2 (ef799d41b|remote/master)]$ arc rust-project develop --stdout -- "/data/users/marwhal/fbsource/fbcode/buck2/app/buck2_action_impl/src/actions/impls/run/mod.rs"
2023-08-14T19:50:21.463478Z  INFO query_owner: rust_project::buck: Querying buck to determine owner files=["/data/users/marwhal/fbsource/fbcode/buck2/app/buck2_action_impl/src/actions/impls/run/mod.rs"]
2023-08-14T19:50:21.895449Z  INFO expand_targets: rust_project::buck: targets=[Target("fbcode//buck2/app/buck2_action_impl:buck2_action_impl-unittest"), Target("fbcode//buck2/app/buck2_action_impl:buck2_action_impl")]
Error: failed to deserialize command output
Caused by:
    0: command `"buck2" "bxl" "prelude//rust/rust-analyzer/resolve_deps.bxl:expand_targets" "--" "--targets" "fbcode//buck2/app/buck2_action_impl:buck2_action_impl-unittest" "fbcode//buck2/app/buck2_action_impl:buck2_action_impl"` (exit code: exit status: 2)
       stderr:
       [2023-08-14T12:50:22.052-07:00] Note: using experimental modern dice.
       [2023-08-14T12:50:22.052-07:00] Buck UI: https://www.internalfb.com/buck2/d86ef843-188f-4c2f-a523-061844228ca6
       [2023-08-14T12:50:22.102-07:00] Network: Up: 0B  Down: 0B
       [2023-08-14T12:50:22.113-07:00] Command failed:
       [2023-08-14T12:50:22.113-07:00] Error evaluating module: `prelude//rust/rust-analyzer/resolve_deps.bxl`
       [2023-08-14T12:50:22.113-07:00]
       [2023-08-14T12:50:22.113-07:00] Caused by:
       [2023-08-14T12:50:22.113-07:00]     Traceback (most recent call last):
       [2023-08-14T12:50:22.113-07:00]       * fbcode/buck2/prelude/rust/rust-analyzer/resolve_deps.bxl:165, in <module>
       [2023-08-14T12:50:22.113-07:00]           expand_and_resolve = bxl(
       [2023-08-14T12:50:22.113-07:00]     error: Operation `call()` not supported on type `struct`
       [2023-08-14T12:50:22.113-07:00]        --> fbcode/buck2/prelude/rust/rust-analyzer/resolve_deps.bxl:165:22
       [2023-08-14T12:50:22.113-07:00]         |
       [2023-08-14T12:50:22.113-07:00]     165 |   expand_and_resolve = bxl(
       [2023-08-14T12:50:22.113-07:00]         |  ______________________^
       [2023-08-14T12:50:22.113-07:00]     166 | |     impl = expand_and_resolve_impl,
       [2023-08-14T12:50:22.113-07:00]     167 | |     cli_args = {
       [2023-08-14T12:50:22.113-07:00]     168 | |         "targets": cli_args.list(cli_args.target_expr()),
       [2023-08-14T12:50:22.113-07:00]     169 | |     },
       [2023-08-14T12:50:22.113-07:00]     170 | | )
       [2023-08-14T12:50:22.113-07:00]         | |_^
       [2023-08-14T12:50:22.113-07:00]         |
       [2023-08-14T12:50:22.113-07:00]
       BXL FAILED
    1: EOF while parsing a value at line 1 column 0
```

I think this D48096437 raced with some other change.

Reviewed By: chatura-atapattu, davidbarsky

Differential Revision: D48327153

fbshipit-source-id: 45743df4920fbbb4f637873febbbc073101bf9f0