buck2: debug file-status: rename '--verbose' into '--show-matches'
Summary:
This is failing on Windows with `mode/win` where clap has extra asserts enabled.

But issue is real and it's not specific to Windows: this option masks common `--verbose` option from `buck2` command itself.

Before:
```
> .\buck2.exe debug file-status --help

thread 'main' panicked at third-party\rust\vendor\clap-3.2.25\src\builder\debug_asserts.rs:110:17:
Command file-status: Long option names must be unique for each argument, but '--verbose' is in use by both 'verbose' and 'verbosity'

> buck2 debug file-status --help
    -v, --verbose

    -v, --verbose <VERBOSITY>
            How verbose buck should be while logging.

            Values: 0 = Quiet, errors only; 1 = Show status. Default; 2 = more info about errors; 3 = more info about
            everything; 4 = more info about everything + stderr;

            It can be combined with specific log items (stderr, full_failed_command, commands, actions, status, stats,
            success) to fine-tune the verbosity of the log. Example usage "-v=1,stderr"

            [default: 1]
```

After:
```
> buck2 debug file-status --help

-s, --show-matches
            Print all matches
```

This rename was suggested when this option was initially added in D46798469.

Reviewed By: scottcao

Differential Revision: D52369980

fbshipit-source-id: e53f559df302d6f3489b38955db0ccaf6046f24c