More detailed somerge cycle error message
Summary:
This confused me quite a bit. D70255661 was failing with the following error:
```
error: fail: cycle in graph detected:

    1: fbsource//xplat/arfx/atlas/modules/anchor/api:apiAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)

 -> 2: libarfx-felios.so
         Reason for edge:
              fbsource//xplat/arfx/atlas/modules/anchor/api:apiAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)
           -> fbsource//xplat/arfx/openxr/support/types:typesAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)

 -> 3: fbsource//xplat/arfx/atlas/modules/anchor/api:apiAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)
         Reason for edge:
              fbsource//xplat/arfx/felios/app/atlas/anchor/api:apiAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)
           -> fbsource//xplat/arfx/atlas/modules/anchor/api:apiAndroid (cfg:android-arm64-r26b-api31-no-san#5453560ffb6ae7d6)

   --> fbcode/buck2/prelude/utils/graph_utils.bzl:99:9
    |
 99 |           fail(
    |  _________^
100 | |             "cycle in graph detected:{}\n".format("".join(errors)),
101 | |         )
    | |_________^
    |
```

Which was odd seeing as xplat/arfx/openxr/support/types:typesAndroid had zero dependencies. It's not a cycle between the buck targets but the libraries (.so) files. It took me a while to realise this from the error message, so making things a bit more explicit.

Reviewed By: nlutsenko

Differential Revision: D70334151

fbshipit-source-id: 37501c4f246289ff0f8a8079fd33ad40012189b6