re_grpc: consider network interruptions retryable (#1460)
Summary:
Right now, intermittent network failures like these fail the build immediately:

```
Error: (Failed to make BatchReadBlobs request: code: 'The operation was
cancelled', message: "operation was canceled", source: tonic::transport::Error(
Transport, hyper::Error(Canceled, "connection closed")): transport error:
operation was canceled: connection closed)
```

Add `Cancelled` cause to list of retryable errors.

Pull Request resolved: https://github.com/facebook/buck2/pull/1460

Reviewed By: 8Keep

Differential Revision: D115854815

fbshipit-source-id: 689c2b9061cd2afd5f9c2d1a77383065b688b261