error: Fix doc comment
Summary: Was out of date. Add doc links so that this breaks next time the method name is changed

Reviewed By: blackm00n

Differential Revision: D57909044

fbshipit-source-id: 5c2aa0dd8de104f5703effc58b0dfc8040bb1b12