buck2/prelude: check basename of soname in cxx.bzl
Summary:
It seems we allow target name to contain `/`. This means `soname` may contain `/` as well.

So here we need to compare basename against basename. Otherwise we get this:
```
Error running analysis for `fbcode//buck2/tests/targets/rules/cxx/soname_lib:check-static (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#92bf57714f78c9a1)`

Caused by:
    0: Error running analysis for `fbcode//buck2/tests/targets/rules/cxx/soname_lib:subdir/libfoo.a (ovr_config//platform/linux:x86_64-fbcode-platform010-clang#92bf57714f78c9a1)`
    1: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/prelude/cxx/cxx.bzl:475, in prebuilt_cxx_library_impl
             soname_lib = ctx.actions.copy_file(soname, shared_lib.output)
       error: Multiple artifacts and/or metadata files are declared at the same output location `libsubdir/libfoo.a.so` declared at `fbcode/buck2/prelude/cxx/link.bzl:423:18-52`.
          --> fbcode/buck2/prelude/cxx/cxx.bzl:475:38
           |
       475 |                         soname_lib = ctx.actions.copy_file(soname, shared_lib.output)
           |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

Reviewed By: akrieger

Differential Revision: D51308717

fbshipit-source-id: 65d64056908408946791b689d24c8ad7930d7877