allow read_dotslash_file to retry on ESTALE err
Summary:
The NFS ESTALE error is transient and can be retried. The error indicates that the file handle that was used to make a request is no longer valid, and the request should be retried with a new handle. See D69892541 diff summary for more context.

On D69892541, we added ESTALE error to the list of retriable errors in `fs_util` functions. However, we have some function like `read_dotslash_file` function that doesn't use `fs_util` functions to read file. I had some instance of errors like this
```
kavehahmadi@kavehahmadi-mbp fbcode % buck2 build mode/mac eden/fs/...
Error: Could not read dotslash file /Users/kavehahmadi/fbsource-dev/tools/buck2-versions/stable: Stale NFS file handle (os error 70)
```
To apply the retry on these errors, this diff modifies the `read_dotslash_file` function then it will be retried on ESTALE err.
Instead of `tokio::fs::read_to_string` we can use `buck2_core::fs::fs_util::read_to_string` then it will retry on reading the dotslash files.

Reviewed By: JakobDegen

Differential Revision: D70662956

fbshipit-source-id: ea752958b56ec89aa2729e5c0aa36bd520c9444d