Link libcrypto with -lc
libcrypto requires the atexit symbol from libc.

```
  = note: /usr/bin/ld: shim/third-party/cxx/vendor/openssl-linux/lib/x86_64-linux-gnu/libcrypto.a(libcrypto-lib-init.o): in function `ossl_init_register_atexit_ossl_':
          (.text+0x200): undefined reference to `atexit'
          collect2: error: ld returned 1 exit status
```