Allow `None` in `LinkerInfo.linker_flags`. (#593)
Summary:
Allow `None` in `LinkerInfo.linker_flags`.

[`LinkerInfo.linker_flags`] field is by default set to `None`, as well as other
flag list fields (e.g. [`LinkerInfo.archiver_flags`]).

However, [`LinkerInfo.linker_flags`] isn't consistenly used across `prelude`.

For instance, in [`cxx/cxx_library.bzl`], [`LinkerInfo.linker_flags`] is treated
as an optional list:

https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_library.bzl#L774

On the other hand, in [`cxx/cxx_toolchain_types.bzl`], [`LinkerInfo.linker_flags`]
is expected to contain a non-`None` value:

https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_toolchain_types.bzl#L308

https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_toolchain_types.bzl#L327

This leads to an error when defining a custom CXX toolchain:

```
Caused by:
    0: Error running analysis for `toolchains//:cxx (prelude//platforms:default#904931f735703749) (prelude//platforms:default#904931f735703749)`
    1: Traceback (most recent call last):
         File <builtin>, in <module>
         * musl-toolchain/define_toolchain.bzl:53, in _define_cxx_toolchain_impl
             ] + cxx_toolchain_infos(
         * prelude/cxx/cxx_toolchain_types.bzl:308, in cxx_toolchain_infos
             "ldflags-shared": _shell_quote(linker_info.linker_flags),
         * prelude/cxx/cxx_toolchain_types.bzl:328, in _shell_quote
             return cmd_args(xs, quote = "shell")
       error: Expected `a value implementing CommandLineArgLike (str, Artifact, RunInfo, etc)`, but got `NoneType`
          --> prelude/cxx/cxx_toolchain_types.bzl:328:12
           |
       328 |     return cmd_args(xs, quote = "shell")
           |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

This commit handles the [`LinkerInfo.linker_flags`] consistently
across the project.

[`LinkerInfo.linker_flags`]: https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_toolchain_types.bzl#L41
[`LinkerInfo.archiver_flags`]: https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_toolchain_types.bzl#L20
[`cxx/cxx_library.bzl`]: https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_library.bzl
[`cxx/cxx_toolchain_types.bzl`]: https://github.com/facebook/buck2/blob/1e89af6622344c46543a9e3781a556e058471043/prelude/cxx/cxx_toolchain_types.bzl

Pull Request resolved: https://github.com/facebook/buck2/pull/593

Reviewed By: ndmitchell

Differential Revision: D54732694

Pulled By: JakobDegen

fbshipit-source-id: 4c0bd711cecdce45c1b4f1329962cebaf2cca9d4