buck2_error: Derive macro ergonomics: Implement typ
Summary:
Support for specifying the type of the error.

This uses the same `typ` which is used elsewhere. Yay for consistency, yay for not using a keyword, meh on the actual name. Leave better ideas if you have them

Reviewed By: stepancheg

Differential Revision: D50689221

fbshipit-source-id: b14d024bc9f7e25d70ba1a2d9af207e919693432