fix broken OSS buck test
Summary:
Buck windows CI doesn't like the unused variable

```
error: unused variable: `executable`
   --> app\buck2_core\src\fs\fs_util.rs:473:51
    |
473 | pub fn set_executable<P: AsRef<AbsPath>>(path: P, executable: bool) -> buck2_error::Result<()> {
    |                                                   ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_executable`
    |
    = note: requested on the command line with `-D unused-variables`

error: could not compile `buck2_core` (lib) due to 1 previous error
```

https://github.com/facebook/buck2/actions/runs/15495890581/job/43632406472

Created from CodeHub with https://fburl.com/edit-in-codehub

Reviewed By: anaypaul

Differential Revision: D76143882

fbshipit-source-id: 2fcc5153ba40fb5e4eb1316ef6faba02d91a1f1b