buck2_error: Use `recover_crate_error` more consistently
Summary: This doesn't do anything yet in most of the branches it's used in, ie it basically only makes sense in the `From<anyhow::Error>` impl. However, this will change in the next few diffs

Reviewed By: stepancheg

Differential Revision: D50934111

fbshipit-source-id: 2a9ccb3418a26d44eedba32b10a89355b8be3a15