Fix package boundary violations in buck2_explain
Summary:
This is not an error in fbsource but it breaks `buck2 utargets ...` in the open-source repo.

```lang=text,counterexample
Error parsing gh_facebook_buck2//app/buck2_explain
Error evaluating build file: `gh_facebook_buck2//app/buck2_explain:BUCK`

Caused by:
    0: Traceback (most recent call last):
         * app/buck2_explain/BUCK:35, in <module>
             buck_genrule(
         * shim/build_defs/native_rules.bzl:10, in buck_genrule
             native.genrule(visibility = visibility, **kwargs)

       error: Error coercing attribute `srcs` of `gh_facebook_buck2//app/buck2_explain:output_format_schema_rust`
         --> shim/build_defs/native_rules.bzl:10:5
          |
       10 |     native.genrule(visibility = visibility, **kwargs)
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
    1: Error coercing attribute `srcs` of type `attrs.one_of(attrs.dict(attrs.string(), attrs.source(), sorted=False), attrs.list(attrs.source()), default=[])`
    2: Error coercing ["output_format_js/output_format.fbs"]
    3: one_of fails, the errors against each alternative in turn were:
       Expected `dict`, but got `list (repr: ["output_format_js/output_format.fbs"])`
       Error coercing "output_format_js/output_format.fbs": Coercing `output_format_js/output_format.fbs` as a source: Source file `output_format_js/output_format.fbs` does not exist as a member of package `gh_facebook_buck2//app/buck2_explain`.
```

Reviewed By: JakobDegen

Differential Revision: D74543321

fbshipit-source-id: dc2bd9de6da99314a3487d440be952f1debbc552