buck2_error: Remove downcasting support
Summary: Now that it's no longer used

Reviewed By: iguridi

Differential Revision: D52022089

fbshipit-source-id: b87ac0cdd72fcb5004caddaea6b66e4eb7a7a2f2