Add default_target_platform to ci_hint
Summary:
In D112498686, I'm adding a `bxl_test` (which uses `buck2_e2e_test`
under the hood) which needs a `ci_srcs` for proper CI functioning. I
like to run `buck build //my/package/...` as a quick check, and it was
failing after the `ci_srcs` addition:

```
$ buck build '//third-party/llvm-project/gator/20/llvm-project/lld/unittests:ci_hint@verify_unit_tests'
BUILD FAILED
Error running analysis for `fbsource//third-party/llvm-project/gator/20/llvm-project/lld/unittests:ci_hint@verify_unit_tests (cfg:linux-x86_64-clang19#3989acef43d5d22d)`
Caused by:
    0: Error running analysis for `fbsource//third-party/llvm-project/gator/20/llvm-project/lld/unittests:verify_unit_tests (cfg:linux-x86_64-clang19#3989acef43d5d22d)`
    1: Error running analysis for `fbcode//tools/build/buck/wrappers:dummy-omnibus-target (cfg:linux-x86_64-clang19#3989acef43d5d22d)`
    2: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/prelude/cxx/cxx.bzl:235, in cxx_library_impl
             return cxx_library_generate(ctx, "cxx_library")
         * fbcode/buck2/prelude/cxx/cxx.bzl:263, in cxx_library_generate
             error_handler = get_cxx_toolchain_info(ctx).cxx_error_handler,
         * fbcode/buck2/prelude/cxx/cxx_context.bzl:43, in get_cxx_toolchain_info
             fail("no cxx toolchain info in this ctx")
       error: fail: no cxx toolchain info in this ctx
         --> fbcode/buck2/prelude/cxx/cxx_context.bzl:43:9
          |
       43 |         fail("no cxx toolchain info in this ctx")
          |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
```

Give the generated `ci_hint` an appropriate `default_target_platform` to
fix this. I tried to do this for all `ci_hint` uses in D112840624, but
that caused WhatsApp stable breakages, and in general the blast radius
of that approach is pretty high. I'm now scoping to just the `ci_hint`
in `buck2_e2e_test`, which should be pretty safe and match the platform
of the underlying Python test targets. The logic there is hard to follow
since it flows through many layers, but for posterity:
* https://fburl.com/code/gtpqkghh calls `python_pytest` without any
  explicit `platform` set.
* That eventually reaches https://fburl.com/code/vdvnphwu, which calls
  `python_common.convert_binary` with `base_path = native.package_name()`
  (no one has set `platform` or `default_target_platform` in the meantime).
* https://fburl.com/code/2wsljfnk calls `get_cxx_platform_for_base_path`
  with that `base_path`, and https://fburl.com/code/s0ed8ms2 sets
  `default_target_platform` to `cxx_platform.target_platform`, exactly
  matching the logic in this diff.

Reviewed By: mzlee

Differential Revision: D113103550

fbshipit-source-id: 4a78a44e71131a0071e604a1bcaf733c3ec194fe