buck2_error: Make a return type optional
Summary: Small refactor to make the next diff easier. Also adds some tests for bugs I almost wrote

Reviewed By: wendy728

Differential Revision: D51057847

fbshipit-source-id: 5e701058c6397b5a30c120a3bf8bdbeadcf4b838