Include preprocessor flags in buildscript C compiler shim
Summary:
Some C++ toolchains (CxxToolchainInfo) put flags like `-isystem` and `-resource-dir` into `preprocessor_flags`, providing a non-buckified standard library or platform headers. This is the case for our `fbsource//xplat/toolchains/redhat:centos9` toolchain.

Without providing these preprocessor flags to build scripts, C/C++ code compiled by a build script can fail with missing headers.

```lang=log,counterexample
Action failed: fbsource//third-party/rust/vendor/aws-lc-sys:0.39-build-script-main-run (buildscript)
In file included from /re_cwd/buck-out/v2/art/fbsource/22e04992ba7633f9/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/third_party/jitterentropy/jitterentropy-library/src/jitterentropy-timer.c:22:
In file included from /re_cwd/buck-out/v2/art/fbsource/22e04992ba7633f9/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/third_party/jitterentropy/jitterentropy-library/src/jitterentropy-timer.h:23:
In file included from /re_cwd/buck-out/v2/art/fbsource/22e04992ba7633f9/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/third_party/jitterentropy/jitterentropy-library/src/jitterentropy-internal.h:45:
In file included from /re_cwd/buck-out/v2/art/fbsource/22e04992ba7633f9/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/third_party/jitterentropy/jitterentropy-library/jitterentropy.h:168:
/re_cwd/buck-out/v2/art/fbsource/22e04992ba7633f9/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/third_party/jitterentropy/jitterentropy-library/jitterentropy-base-user.h:52:10: fatal error: 'sys/types.h' file not found
   52 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
1 error generated.
```

```lang=log,counterexample
Action failed: fbsource//third-party/rust/vendor/aws-lc-sys:0.39-build-script-main-run (buildscript)
thread 'main' (2714567) panicked at third-party/rust/vendor/aws-lc-sys-0.39.0/builder/cc_builder.rs:712:9:
COMPILER: /re_cwd/buck-out/v2/art/fbsource/a6f163408828dea0/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/__cc_shim.sh
ARGS: ["-Wall", "-Wextra", "/re_cwd/buck-out/v2/art/fbsource/a6f163408828dea0/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "/re_cwd/buck-out/v2/art/fbsource/a6f163408828dea0/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/OUT_DIR/memcmp_invalid_stripped_check"]
ERROR:
/re_cwd/buck-out/v2/art/fbsource/a6f163408828dea0/third-party/rust/vendor/aws-lc-sys/__0.39-build-script-main-run__/cwd/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c:4:10: fatal error: 'stdio.h' file not found
    4 | #include <stdio.h>
      |          ^~~~~~~~~
1 error generated.
```

Reviewed By: athmasagar

Differential Revision: D98439032

fbshipit-source-id: 7d0bf33688a360f777ec8774791f4128813d2ea4