Remove --help reference to nonexistent --show-rulekey flag
Summary:
The `--help` for this flag says that it's incompatible with `--show-rulekey`, but that option does not exist in `buck2 targets`:

```
> buck2 targets --show-rulekey
error: Found argument '--show-rulekey' which wasn't expected, or isn't valid in this context

	Did you mean '--show-output'?

	If you tried to supply `--show-rulekey` as a value rather than a flag, use `-- --show-rulekey`

USAGE:
    buck2 targets --show-output

For more information try --help
```

So this statement doesn't make sense.

Created from CodeHub with https://fburl.com/edit-in-codehub

Reviewed By: stepancheg

Differential Revision: D47469840

fbshipit-source-id: 95cd800c796c72ab9fda840ca573f137b2607949