buck2_error: Regrettably, `impl Context for Option<T>`
Summary: I know I said earlier we shouldn't do this. I still believe that. However, we seem to use this in a lot of places, so this might be hard to get away from. Let's impl it for now, and try to use actual error types in the future

Reviewed By: stepancheg

Differential Revision: D48672467

fbshipit-source-id: 13a71ea799e0cb14864c8279de7bca0b8c95b138