Improve missing dependency error message
Summary:
Error message example:
```
BUILD FAILED
Error running dynamic analysis for `fbcode//tools/go/fbgo:fbgo (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#1b404c280599ee8e)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/buck2/prelude/go/package_builder.bzl:230, in _build_package_action_impl
          non_shared_x, non_shared_a = build_variant(shared = False)
      * fbcode/buck2/prelude/go/package_builder.bzl:198, in build_variant
          importcfg = make_compile_importcfg(
      * fbcode/buck2/prelude/go/packages.bzl:146, in make_compile_importcfg
          fail(message)
    error: fail: Missing dependencies for imports (check BUCK file):
      - golang.org/x/mod/modfile
      - golang.org/x/tools/go/analysis

       --> fbcode/buck2/prelude/go/packages.bzl:146:9
        |
    146 |         fail(message)
        |         ^^^^^^^^^^^^^
        |
```

Reviewed By: echistyakov, IanChilds

Differential Revision: D94529474

fbshipit-source-id: e0bc07946ff5f51e0ebf8c641c85dcb64b821d07