Fix the system cxx toolchain
Summary:
D70723680 broke the `system_cxx_toolchain` because it doesn't have the `supports_two_phase_compilation` attr.

https://www.internalfb.com/code/fbsource/[f87e09a34771dcc134e4c8855a3543ddad842a6c]/fbcode/buck2/prelude/toolchains/cxx.bzl?lines=216-240

Error:
```
    4: Traceback (most recent call last):
         File <builtin>, in <module>
         * tools/buck2/prelude/toolchains/cxx.bzl:88, in _system_cxx_toolchain_impl
             return _cxx_toolchain_from_cxx_tools_info(ctx, cxx_tools_info, target_name)
       error: Object of type `struct` has no attribute `supports_two_phase_compilation`
          --> tools/buck2/prelude/toolchains/cxx.bzl:177:50
           |
       177 |                 supports_two_phase_compilation = ctx.attrs.supports_two_phase_compilation,
           |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

***We could add this attr to `system_cxx_toolchain` and default to False (as done elsewhere), but this seems like leaking custom toolchain implementation to the simple toolchain that we're trying to define.***

Thus, changed the code to see if the we're working with a toolchain with the attribute, and if so set it, else default to False.

Reviewed By: ezgicicek

Differential Revision: D70775066

fbshipit-source-id: ed104e4f0912880430cefc76de0d025bd53c5522