buck2_error: Remove a wrong comment
Summary: Forgot to take this out at some point. We clearly can

Reviewed By: stepancheg

Differential Revision: D50689264

fbshipit-source-id: 27ca0597c80d9d0aac767746cc30acd1283e1f26