Respect FORCE_RLIB in setting up external debuginfo
Summary:
This is a bug I made in {D48174780}. Rust usually uses the same `dep_link_style` for both Rust and non-Rust dependencies, *except* if dep_link_style is LinkStyle("shared"), in which case it uses static linkage for Rust dependencies and shared linkage for non-Rust dependencies.

https://www.internalfb.com/code/fbsource/[bf5fb722b90a62fdd74276676a7f38f0a26b47a0]/fbcode/buck2/prelude/rust/link_info.bzl?lines=31-36

The propagation of external debug info through the LinkArgs provider did not respect this exception. It incorrectly used the same link style always for Rust and non-Rust dependencies.

This manifested as Rust targets sometimes being built as both static and shared objects, whereas prior to {D47928283} they would be built static only. We'd still only *link* the static artifact, but we'd build the shared artifact to materialize external debuginfo generated by it for dwp invocations.

Not all targets currently support compilation to shared object. In particular, no_std crates.

```
Action failed: fbsource//third-party/rust:link-cplusplus-1.0.9 (rustc dylib-pic-shared-link/link_cplusplus-link dylib,pic,link [diag])

error: `#[panic_handler]` function required, but not found

error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`
```

Reviewed By: zertosh, ayermolo, shayne-fletcher

Differential Revision: D48277737

fbshipit-source-id: 2aa00edb939d6fbb54e8a9e65e18ddbf6e5a6d3f