Pass anonymous_link_groups attribute to prelude (take 2)
Summary:
Original diff {D48709083} was reverted due to this test failure:

```
christylee@devbig381:archive_semantics_test  (a7cd53d30)$ buck2 build @//mode/opt-clang-thinlto -c fbcode.use_link_groups=True -c fbcode.enable_distributed_thinlto=True -c "cxx.extra_cxxflags='-O0'" :main_bin
Watchman fresh instance: new mergebase, cleared graph state, cleared dep files
Action failed: fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (thin_lto_index_link_group libshared_lib_2.so)
Local command returned non-zero exit code 1
Reproduce locally: `env -- "BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/a ...<omitted>... ps/archive_semantics_test/__main_bin__/__action__20__/libshared_lib_2.so_thin_lto_index_link_group/" (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
ld.lld: error: cannot open output file buck-out/v2/gen/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/archive_semantics_test/__main_bin__/__link_groups__/libshared_lib_2.so: No such file or directory
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "buck-out/v2/gen/prelude/1c1d3b4205714387/cxx/dist_lto/tools/__dist_lto_planner__/dist_lto_planner.py", line 319, in <module>
    sys.exit(main(sys.argv))
  File "buck-out/v2/gen/prelude/1c1d3b4205714387/cxx/dist_lto/tools/__dist_lto_planner__/dist_lto_planner.py", line 75, in main
    subprocess.check_call(args.index_args[1:])
  File "/usr/local/fbcode/platform010/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['buck-out/v2/gen/fbcode/1c1d3b4205714387/tools/build/buck/wrappers/__ld__/ld', '--ld=fbcode/third-party-buck/platform010/build/llvm-fb/12/bin/clang++', '--cc=buck-out/v2/gen/fbcode/1c1d3b4205714387/tools/build/buck/wrappers/__fbcc__/fbcc --cc=fbcode/third-party-buck/platform010/build/llvm-fb/12/bin/clang --target=x86_64-redhat-linux-gnu -nostdinc -resource-dir fbcode/third-party-buck/platform010/build/llvm-fb/12/lib/clang/stable -idirafter fbcode/third-party-buck/platform010/build/llvm-fb/12/lib/clang/stable/include -idirafter fbcode/third-party-buck/platform010/build/glibc/include -idirafter fbcode/third-party-buck/platform010/build/kernel-headers/include -Bfbcode/third-party-buck/platform010/build/binutils/x86_64-facebook-linux/bin', '--cflag=--target=x86_64-redhat-linux-gnu', '--ar=fbcode/third-party-buck/platform010/build/llvm-fb/12/bin/llvm-ar', '-Bfbcode/third-party-buck/platform010/build/glibc/lib', '-Bfbcode/third-party-buck/platform010/tools/gcc/lib/gcc/x86_64-redhat-linux-gnu/trunk', '-Lfbcode/third-party-buck/platform010/build/libgcc/lib/gcc/x86_64-facebook-linux/trunk', '-Wl,-nostdlib', '-Wl,--dynamic-linker,/usr/local/fbcode/platform010/lib/ld.so', '-Wl,--disable-new-dtags', '-Bfbcode/third-party-buck/platform010/build/binutils/x86_64-facebook-linux/bin', '-Bbuck-out/v2/gen/fbcode/1c1d3b4205714387/third-party-buck/platform010/build/llvm-fb/12/__lld_path__/lld_path/bin', '-Wl,--no-mmap-output-file', '-nodefaultlibs', '--target=x86_64-redhat-linux-gnu', '-Lfbcode/third-party-buck/platform010/build/glibc/lib', '-Lfbcode/third-party-buck/platform010/build/libgcc/lib', '-Wl,-z,notext', '-Wl,-z,relro', '-Wl,--gc-sections', '-fuse-ld=lld', '-Wl,--discard-section=.nv_fatbin', '-Wl,--discard-section=.nvFatBinSegment', '-Wl,--discard-section=__nv_relfatbin', '-Wl,--discard-section=__nv_module_id', '-Wl,--discard-section=.rela.debug_info', '-Wl,--discard-section=.rela.debug_ranges', '-Wl,--discard-section=.rela.debug_loc', '-Wl,--discard-section=.rela.debug_line', '-Wl,--discard-section=.rela.debug_aranges', '-Wl,--discard-section=.rela.debug_types', '-Wl,-O1', '-Wl,--build-id=sha1', '-fexperimental-new-pass-manager', 'buck-out/v2/gen/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/archive_semantics_test/__main_bin__/libshared_lib_2.so.thinlto.index.argsfile', '-o', 'buck-out/v2/gen/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/archive_semantics_test/__main_bin__/__link_groups__/libshared_lib_2.so', '-Wl,--thinlto-index-only=buck-out/v2/gen/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/archive_semantics_test/__main_bin__/__action__20__/libshared_lib_2.so_thin_lto_index_link_group/index', '-Wl,--thinlto-emit-imports-files', '-Wl,--thinlto-full-index', '-Wl,--thinlto-prefix-replace=;buck-out/v2/gen/fbcode/674d282f257e9e27/tools/build/test/cpp/link_groups/archive_semantics_test/__main_bin__/__action__20__/libshared_lib_2.so_thin_lto_index_link_group/']' returned non-zero exit status 1.
Buck UI: https://www.internalfb.com/buck2/60283107-c274-4ad7-bd32-a8fdce90c6e0
Note:    Using experimental modern dice
Network: Up: 204KiB  Down: 106MiB  (reSessionID-eb94002d-6007-493d-a59d-ad7eb772f6c5)
Jobs completed: 1370. Time elapsed: 5.7s.
Cache hits: 50%. Commands: 64 (cached: 32, remote: 16, local: 16)
BUILD FAILED
for action key `(target: `fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-python-3.10#674d282f257e9e27)`, id: `153`)`: for action key `(target: `fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-python-3.10#674d282f257e9e27)`, id: `34`)`: Failed to build 'fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-python-3.10#674d282f257e9e27)'
for action key `(target: `fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-python-3.10#674d282f257e9e27)`, id: `34`)`: Failed to build 'fbcode//tools/build/test/cpp/link_groups/archive_semantics_test:main_bin (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-python-3.10#674d282f257e9e27)'
```

Anon targets are not yet compatible with dynamic outputs. Previously we disabled anon link groups when building link group shared library with distributed thinlto, but final link still expected the output path to be the anon output path. Disabling distributed thinlto when linking link group shared libraries as anon targets instead fixes the issue.

Reviewed By: athmasagar, luciang

Differential Revision: D48914458

fbshipit-source-id: 81f6e16ea4a92c7bd80f374f3049402e2bedef37