Try to fix cargo build
Summary:
See jobs on previous diff, e.g. https://www.internalfb.com/sandcastle/workflow/562949953427217682

```
error: failed to select a version for `blake3`.
    ... required by package `buck2 v0.1.0 (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/app/buck2)`
versions that meet the requirements `^1.3.1` are: 1.5.2

the package `buck2` depends on `blake3`, with features: `digest` but `blake3` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

failed to select a version for `blake3` which could resolve this conflict
```

This fixes the build, though I don't really know what I'm doing so if there's a better way, please lmk

Reviewed By: samkevich

Differential Revision: D69300972

fbshipit-source-id: 7eca664db4ef3b6bc46486fb4330651b12c18c06