Bump rustls for client_auth_cert method (#553)
Summary:
It was added in the 0.21.5 point release.
Errors took the following form:

    $ ~/task/buck2 cargo build
    error[E0599]: no method named `with_client_auth_cert` found for struct `ConfigBuilder` in the current scope
       --> app/buck2_http/src/tls.rs:126:10
        |
    123 | /     ClientConfig::builder()
    124 | |         .with_safe_defaults()
    125 | |         .with_root_certificates(system_roots)
    126 | |         .with_client_auth_cert(cert, key)
        | |         -^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `with_no_client_auth`
        | |_________|

Pull Request resolved: https://github.com/facebook/buck2/pull/553

Reviewed By: zertosh

Differential Revision: D53215853

Pulled By: dtolnay

fbshipit-source-id: 8ab3616c1335330e94bfe28eb14304178803fe8e