buck2_error: Remove `DisplayAndAny`
Summary: We stored context in a typed way to be able to support downcasting. No more downcasting means no more typed context, so we can clean up a bunch of code

Reviewed By: iguridi

Differential Revision: D52022090

fbshipit-source-id: 3b620936c36e9855c8ed827e051349b0b97f9965