expose numpy .h files when building
Summary:
fix for cases where the #include was missing
```
  gcc -fno-strict-overflow -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -O3 -g -pipe -Wno-error -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fno-omit-frame-pointer -momit-leaf-frame-pointer -gz=none -Wl,-z,relro -fcommon -gdwarf-4 -fno-reorder-blocks-and-partition -gstrict-dwarf -nostdinc -grecord-gcc-switches -march=core-avx2 -mtune=skylake -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/merged_python/numpy/core/include -I/usr/local/python/include/python3.12 -c /mnt/srcs/src/cftime/_cftime.c -o build/temp.linux-x86_64-cpython-312/mnt/srcs/src/cftime/_cftime.o
  /mnt/srcs/src/cftime/_cftime.c:1214:10: fatal error: numpy/arrayobject.h: No such file or directory
   1214 | #include "numpy/arrayobject.h"
```

Add the raw_headers to the container, and add the public includes so that we know where to find the files

Reviewed By: andrewjcg

Differential Revision: D93818711

fbshipit-source-id: 4202983ab1153eacf8bcd22c24f7d13006ccb3af