Bump ipnetwork version to 0.20.0
Summary:
Fix this

```
[92mRunning clippy[0m
    Updating git repository `https://github.com/krallin/perf-event.git`
From https://github.com/krallin/perf-event
 * [new ref]         86224a9bc025d5d19f719542f27c8c629a08b167 -> refs/commit/86224a9bc025d5d19f719542f27c8c629a08b167
    Updating git repository `https://github.com/get9/hyper-proxy`
From https://github.com/get9/hyper-proxy
 * [new ref]         205e9fee42d469444d654d9fa207897f4a77d5b6 -> refs/commit/205e9fee42d469444d654d9fa207897f4a77d5b6
error: failed to select a version for the requirement `ipnetwork = "^0.15"`
candidate versions found which didn't match: 0.20.0
location searched: directory source `/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/../../third-party/rust/vendor` (which is replacing registry `crates-io`)
required by package `buck2_http v0.1.0 (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/app/buck2_http)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Reviewed By: get9, lmvasquezg

Differential Revision: D50331007

fbshipit-source-id: ae9053f6080eed241933572044ee977425ff9302