Move the src files out of the argsfile
Summary:
In Xcode, we expect the argsfile to have the compile args, not the sources themselves.

But all swift files have the same compile args, so in D30282387, they were all added to the same command. Conversion to the use of an argsfile did not take this into account. So the argsfile has the sources:

```
cat /Users/chatatap/fbsource/buck-out/v2/gen/fbsource/56628b5feecfab0a/fbobjc/buck2/samples/hello_world/__ViewController__/swift_compile.argsfile
-working-directory
.
-sdk
/var/db/xcode_select_link/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk
-target
x86_64-apple-ios15.0-simulator
-wmo
-module-name
ViewController
-parse-as-library
-Xfrontend
-no-clang-module-breadcrumbs
-swift-version
5
fbobjc/buck2/samples/hello_world/srcs/ViewController.swift
```

This is problematic in Xcode, because Xcode indexes each file separately, and we hit the following error:
```
error: filename "ViewController.swift" used twice: '/Users/chatatap/fbsource/fbobjc/buck2/samples/hello_world/srcs/ViewController.swift' and '/Users/chatatap/fbsource/fbobjc/buck2/samples/hello_world/srcs/ViewController.swift'
note: filenames are used to distinguish private declarations with the same nam
```

The fix is simple, pull the srcs out of the argsfile itself. They can be added to the command line later during the actual compile.

Reviewed By: krallin

Differential Revision: D40574264

fbshipit-source-id: 315006ff609f140385cae1b725766242aedadeea