Better error message when test library has no sources
Summary:
This case keeps happening so let's at least produce a better error message.

```lang=bash
buck2 build fbandroid/javatests/com/facebook/wearable/apps/journal/home

When running analysis for `fbsource//fbandroid/javatests/com/facebook/wearable/apps/journal/home:home (ovr_config//platform/linux:host-test-platform010-clang-nosan-7c5c7030ecb14633)`

Caused by:
    Traceback (most recent call last):
      * fbcode/buck2/prelude/android/robolectric_test.bzl:75, in <module>
          external_runner_test_info = build_junit_test(
    error: Object of type `NoneType` has no attribute `full_library`
      --> fbcode/buck2/prelude/java/java_test.bzl:94:9
       |
    94 |         tests_java_library_info.library_output.full_library,
       |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
```

Reviewed By: bobyangyf

Differential Revision: D43575328

fbshipit-source-id: 068b6996bb5de1283d5cf97fc41180fc6fe18f0f