buck2_error: Use stronger type for context
Summary: So that we can downcast context

Reviewed By: stepancheg

Differential Revision: D50213721

fbshipit-source-id: cf126dae4a9f7715e6105f106b7f5a1e0e2c845d