Fix linkgroup errors for go libraries exported to C
Summary:
Fixing error
```
buck2 run fbcode//tutorials/go/cgo/c_archive:cpp_bin                                                                                      4s
File changed: fbcode//tutorials/PACKAGE
Buck UI: https://www.internalfb.com/buck2/e7452bc4-536c-4139-8cd5-753809acca8d
Network: Up: 0B  Down: 0B
Loading targets.   Remaining     0/2                                                                     44 targets declared
Analyzing targets. Remaining     0/4
Command: run.
Time elapsed: 0.0s
BUILD FAILED
Error running analysis for `fbcode//tutorials/go/cgo/c_archive:cpp_bin (cfg:dev-linux-x86_64-fbcode-platform010-clang17-asan-ubsan-dev#b7ccea4ecf986810)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/buck2/prelude/cxx/cxx.bzl:292, in cxx_binary_impl
          output = cxx_executable(ctx, params)
      * fbcode/buck2/prelude/cxx/cxx_executable.bzl:377, in cxx_executable
          linked_link_groups = create_link_groups(
      * fbcode/buck2/prelude/cxx/link_groups.bzl:1035, in create_link_groups
          roots = _find_all_relevant_roots(
      * fbcode/buck2/prelude/cxx/link_groups.bzl:746, in _find_all_relevant_roots
          depth_first_traversal_by(
      * fbcode/buck2/prelude/utils/graph_utils.bzl:240, in depth_first_traversal_by
          fail("Expected node {} in graph nodes".format(node_formatter(node)))
    error: fail: Expected node fbcode//tutorials/go/cgo/c_archive:cgo (cfg:dev-linux-x86_64-fbcode-platform010-clang17-asan-ubsan-dev#b7ccea4ecf986810) in graph nodes
       --> fbcode/buck2/prelude/utils/graph_utils.bzl:240:13
        |
    240 |             fail("Expected node {} in graph nodes".format(node_formatter(node)))
        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The issue is that regular Go libraries (`go_library` rule) doesn't produce any C-linkable artifacts.
The `go_exported_library` does it (that's go we do C -> Go interop).
The linkgroup implementation exprects some number of data structures to be present, so I'm adding empty ones (looking at Ocaml).
However it would be nice if some domain-expert can remove the need to do this hack.

Reviewed By: echistyakov

Differential Revision: D73628336

fbshipit-source-id: 412ed88a61cd674c70501bd3981a946c8d70d014