Fix $RUST_TARGET_PATH
Summary:
1. Since `toolchain_info.rust_target_path` is a path, make `rustc_action.py` translate it to an absolute path by using `path_env` instead of `plain_env`.

2. Check for `None`. Without this, rustdoc and rustdoc tests fail when no `rust_target_path` is set.

```lang=log,counterexample
Error running analysis for `root//rust:test (prelude//platforms:default#5aa105d386c6913d)`

Caused by:
    0: Error running analysis for `root//rust:library (prelude//platforms:default#5aa105d386c6913d)`
    1: Traceback (most recent call last):
         File <builtin>, in <module>
         * prelude/rust/rust_library.bzl:262, in rust_library_impl
             rustdoc = generate_rustdoc(
       error: Operation `[]` not supported for types `NoneType` and `default_info_callable`
          --> prelude/rust/build.bzl:149:37
           |
       149 |     plain_env["RUST_TARGET_PATH"] = toolchain_info.rust_target_path[DefaultInfo].default_outputs[0]
           |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

overriding_review_checks_triggers_an_audit_and_retroactive_review
Oncall Short Name: rust_foundation

Differential Revision: D88542481

fbshipit-source-id: a18493cfc9787efc2c8f54e5e6c3e4abdd2795c9