Breakpoint
Summary:
Fix error in oss-build:

```
error: missing documentation for a struct
   --> starlark/src/debug/adapter/mod.rs:139:1
    |
139 | pub struct Breakpoint {
    | ^^^^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> starlark/src/lib.rs:384:9
    |
384 | #![deny(missing_docs)]
    |         ^^^^^^^^^^^^
```

I don't know why it fails only in OSS builds.

This type is not used in public API, so made it `pub(crate)` instead of writing a rustdoc.

Reviewed By: JakobDegen

Differential Revision: D47907542

fbshipit-source-id: 78cc0e04961131eb8fed9fe95e6277c9c872ee2f