Replace expect with context in buck2_test
Summary: Replace `expect` with `context` so it fails properly instead of panic. Error dashboard for `buck2 test` currently has a lot `null` errors with no error tag and no error message. The hypothesis is that it panicked at one of these expects so getting rid of them

Reviewed By: IanChilds

Differential Revision: D68480779

fbshipit-source-id: ebc2ff91b4d4a799ccf662031cbc47bc48a0f947