Abbreviate subdirectory of output paths
Summary:
CI is failing on {D73682867} with the following error:

```lang=text,counterexample
Action failed: fbcode//eden/scm/saplingnative/bindings/modules/pyrevisionstore:pyrevisionstore (cfg:opt-windows-x86_64-msvc-clang17-no-san#22e83ae67b4bf3f7) (failure_filter diag)
Remote action, reproduce with: `frecli cas download-action e30dc7db928804472fd94a2d8b310ce03697146e469871c6da4d382cab97af64:144`

error[E0463]: can't find crate for `revisionstore`
  --> fbcode\eden\scm\saplingnative\bindings\modules\pyrevisionstore\src\lib.rs:31:5
   |
31 | use revisionstore::ContentHash;
   |     ^^^^^^^^^^^^^ can't find crate

Missing required input file rlib-pic-static_pic-metadata-fast-diag/libpyrevisionstore-51bbe2c5.rmeta (buck-out\v2\gen\fbcode\22e83ae67b4bf3f7\eden\scm\saplingnative\bindings\modules\pyrevisionstore\__pyrevisionstore__\rlib-pic-static_pic-metadata-fast-diag\libpyrevisionstore-51bbe2c5.rmeta)
```

I tried `buck2 build fbcode//mode/opt-win fbcode//eden/scm/saplingnative/bindings/modules/pyrevisionstore:pyrevisionstore` from a devserver in order to reproduce, and while it did reproduce the exact platform hash that CI was also trying to build (`cfg:opt-windows-x86_64-msvc-clang17-no-san#22e83ae67b4bf3f7`), it did not reproduce the failure. I tried rebasing the diff and CI hit the same failure again in the same target, so it does not seem like one-off corruption.

I checked the CAS action and everything seems to be in order; it **does** contain the file `buck-out/v2/gen/fbcode/22e83ae67b4bf3f7/eden/scm/saplingnative/bindings/modules/pyrevisionstore/__pyrevisionstore__/rlib-pic-static_pic-metadata-fast-diag/libpyrevisionstore-51bbe2c5.rmeta` that the last line of the failure says is missing. I can't see anything wrong except the filepaths being relatively long.

This diff tries abbreviating filepaths to try to create more headroom on Windows systems running with a short filepath length limit.

Reviewed By: JakobDegen

Differential Revision: D73722362

fbshipit-source-id: d3d08b0ccbfbf6e7ee3edf555f68e4de3fc2473a