Fix missing symbol _get_os_release during buck2-based bootstrap on macos
Summary:
Copied from fbsource/third-party/rust:

https://www.internalfb.com/code/fbsource/[0d182602cf2e3912fc9aaaf912233a2e471dea83]/third-party/rust/fixups/sys-info/fixups.toml?lines=1-19

In the Windows case I omitted this line:

https://www.internalfb.com/code/fbsource/[0d182602cf2e3912fc9aaaf912233a2e471dea83]/third-party/rust/fixups/sys-info/fixups.toml?lines=21-22

and whoever first wants to build buck2 on windows using buck2 will figure it out, but at least macos works now.

Tested on both linux and macos:

- `$ reindeer --third-party-dir shim/third-party/rust buckify --stdout > shim/third-party/rust/BUCK`
- `$ buck2 build //:buck2`

**Before:** linux worked but macos fails to link, with:

```
Action failed: root//app/buck2:buck2-bin (rustc bin-pic-static_pic-link/buck2_bin-link bin,pic,link [diag])

error: linking with `buck-out/v2/gen/root/213ed1b7ab869379/app/buck2/__buck2-bin__/__linker_wrapper.sh` failed: exit status: 1
  |
  = note: Undefined symbols for architecture arm64:
            "_get_os_release", referenced from:
                sys_info::os_release::h45dcb59ffafbd5d3 in libsys_info-688a71ed.rlib(sys_info-688a71ed.sys_info.7f956896-cgu.4.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**After:** both work.

Reviewed By: zertosh

Differential Revision: D45608875

fbshipit-source-id: 31e44524bc9beca6ca9b401d0ce71aa68b8a3450