buck2_error: Allow specifying options on enum types
Summary: Instead of having to specify them on each variant, as long as they're the same across all variants

Reviewed By: wendy728

Differential Revision: D51057842

fbshipit-source-id: 4e3ba64cad1c0823bab666bf13767833a81d19c1