buck2_error: introduce http errors for eden network errors
Summary:
Add two specific HTTP error types. As of today, 403 forbidden, 401 unauthorized and 503 service unavailable are the major HTTP errors that Buck2 sees from EdenFS.

Query: https://fburl.com/scuba/buck2_builds/afvk6jz0

Reviewed By: Will-MingLun-Li

Differential Revision: D85215948

fbshipit-source-id: 2e5dd47f62244e111307b825a2094df93be9db4c