Add support to buck2 for running MacroBenchmark tests
Summary:
Jetpack's [Macrobenchmark library](https://developer.android.com/topic/performance/benchmarking/macrobenchmark-overview) relies on instrumentation test infra to provide the ability to:
- Run a test apk and an *apk under test* in 2 different processes
- Have a test apk be self instrumented instead of instrumenting the *apk under test*

Gradle already supports this functionality so the goal of this diff is to achieve feature parity with gradle for successfully running MacroBenchmark tests.  Similar to [gradle](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/dependency/VariantDependencies.kt;l=109), for this use case, arifact exclusions must be disabled.

Without this change in place, among the errors that will be yielded will be:
    java.lang.AssertionError: ERRORS (not suppressed): NOT-SELF-INSTRUMENTING

I've also added the READ/WRITE External Storage permissions to BaseTestingApkAndroidManifest.xml as the test apk requires these permissions when running Macrobenchmark tests.

Reviewed By: fbvxp, IanChilds

Differential Revision: D53666655

fbshipit-source-id: 298a3c4394242c58ec3d0c3b43c58fa24087fc2d