buck2_error: Represent emitted errors
Summary: As discussed in the RFC. This is needed to be able to propagate error information even if it's already been shown to users. Used later in stack

Reviewed By: cjhopman

Differential Revision: D50213718

fbshipit-source-id: b88ffdc7509cd3e2218a5db616086183ef015fce