Fix github ci windows-build-and-test by allow unused variable
Summary:
https://github.com/facebook/buck2/actions/runs/17330648823/job/49205577725
On github ci windows-build-and-test  we got such issue
```
error: unused variable: `enable_action_cgroup_pool`
   --> app\buck2_common\src\resource_control.rs:119:9
    |
119 |         enable_action_cgroup_pool: bool,
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_enable_action_cgroup_pool`
    |
    = note: requested on the command line with `-D unused-variables`

```
This is because on windows we don't use this flag. Set it to allow unused_variables.
We need to do some refactor later.

Reviewed By: JakobDegen

Differential Revision: D81339160

fbshipit-source-id: 5d6f8ea1c4d2e70cce1cce269e91ce120664de6d