buck2_error: Remove dead code
Summary: Forgot to delete it, but not used anymore

Reviewed By: stepancheg

Differential Revision: D50934098

fbshipit-source-id: 5695cd6e5daebc2e886202e3eee6bdbc2bac0d0d