Wrap system_cxx_toolchain's linker to flatten @files
Summary:
Windows's link.exe does not support nested use of `Silvochka` arguments.

> ["Command files cannot be nested."](https://learn.microsoft.com/en-us/cpp/build/reference/linking?view=msvc-170#link-command-files)

This breaks Buck because we pass one level of nesting using `-Clink-arg=@{}` here:

https://www.internalfb.com/code/fbsource/[cf2fee78f5eb681585fcbb66b83b8792889055f8]/fbcode/buck2/prelude/rust/build.bzl?lines=400-405

while separately `rustc` adds its own second level of nesting on top of it:

https://www.internalfb.com/code/fbsource/[53ddfeccf0c09ab6f044afb87a25bb40b84ac846]/third-party/tp2/rust/1.69.0/rustc-1.69.0-src/compiler/rustc_codegen_ssa/src/back/link.rs?lines=1393%2C1406-1407

 ---

The majority of this diff is mirrored from equivalent code in https://www.internalfb.com/code/fbsource/%5Beddf2a081536b775b4dbdb8d98bb0851703c5f75%5D/fbcode/tools/build/buck/wrappers/ld_win.py. However there were some perplexing differences I had to make.

In fbcode's ld_win.py the write to `new_args_file` happens like this:

https://www.internalfb.com/code/fbsource/[eddf2a081536b775b4dbdb8d98bb0851703c5f75]/fbcode/tools/build/buck/wrappers/ld_win.py?lines=199-200%2C212%2C214-216

```
with tempfile.NamedTemporaryFile(mode="w", delete=False) as new_args_file:
    for argument in final_arguments:
        ...
        new_args_file.write(argument + "\n")
    new_args_file.flush()
    command = [LLVM_LINKER, "@" + new_args_file.name]
    subprocess.run(command, check=True)
```

I spent a lot of time working out why the same thing did not work in GitHub Actions. It failed like this:

```
Traceback (most recent call last):
  File "D:\a\cxx\cxx\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__linker_wrapper__\linker_wrapper.py", line 102, in <module>
    main()
  File "D:\a\cxx\cxx\buck-out\v2\gen\prelude\fb50fd37ce946800\cxx\tools\__linker_wrapper__\linker_wrapper.py", line 94, in main
    subprocess.run(command, check=True)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['link.exe', 'D:\\a\\cxx\\cxx\\buck-out\\v2\\tmp\\root\\fb50fd37ce946800\\third-party\\__proc-macro2-1.0.53-build-script-build__\\rustc\\_buck_871788e481b8cd96\\tmpu1ha11yi']' returned non-zero exit status 1104.
Microsoft (R) Incremental Linker Version 14.35.32217.1
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'D:\a\cxx\cxx\buck-out\v2\tmp\root\fb50fd37ce946800\third-party\__proc-macro2-1.0.53-build-script-build__\rustc\_buck_871788e481b8cd96\tmpu1ha11yi'
```

It turned out the thing that made it work was closing the writer on `new_args_file` (i.e. exiting the `with` block) *before* spawning the subprocess. I am confused about why the internal one works.

Reviewed By: diliop

Differential Revision: D45645497

fbshipit-source-id: eba78e221a58938fb098093050b9f15d56bc9b54