Fix clone_on_copy error
Summary:
`fbcode//buck2/scripts:buck2-oss` has been broken since D89503359 since it introduces an unnecessary `.clone()`:

```
error: using `clone` on type `Duration` which implements the `Copy` trait
  --> app/buck2_build_signals_impl/src/enhancement.rs:80:28
   |
80 |             duration: Some(duration_proto.clone()),
   |                            ^^^^^^^^^^^^^^^^^^^^^^ help: try removing the `clone` call: `duration_proto`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
   = note: `-D clippy::clone-on-copy` implied by `-D clippy::all`
   = help: to override `-D clippy::all` add `#[allow(clippy::clone_on_copy)]`
```

Reviewed By: IanChilds

Differential Revision: D91187770

fbshipit-source-id: ad2c15b6bb4747d6612ea647f5b4d2b0e9e57afe