extend a list of known C++ extensions
Summary:
I needed a temporary broken buck target, so I broke it intentionally in this way: D49740823

And to my surprise I have seen the message about unsupported extentions rather than about missing file:
```
Error running analysis for `fbcode//biggrep/clients/cli:biggrep_client (ovr_config//platform/linux:x86_64-fbcode-platform010-clang15#fdd3fedc5f835a2f)`

Caused by:
    Traceback (most recent call last):
      File <builtin>, in <module>
      * fbcode/buck2/prelude/cxx/cxx.bzl:239, in cxx_binary_impl
          output = cxx_executable(ctx, params)
      * fbcode/buck2/prelude/cxx/cxx_executable.bzl:202, in cxx_executable
          compile_cmd_output = create_compile_cmds(
      * fbcode/buck2/prelude/cxx/compile.bzl:199, in create_compile_cmds
          ext = CxxExtension(".cpp" if header_only else src.file.extension)
    error: Unknown enum element ``, given to `enum(".cpp", ".cc", ".cxx", ".c++", ".c", ".s", ".S", ".m", ".mm", ".cu", ".hip", ".asm", ".asmpp", ".h", ".hpp")`
       --> fbcode/buck2/prelude/cxx/compile.bzl:199:15
        |
    199 |         ext = CxxExtension(".cpp" if header_only else src.file.extension)
        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |
```
I went examining this strange thing and noticed that it is missing some extentions hh and h++, according to biggrep there are 6872 of such files:
```
[chernikava@devvm4182.lla0 /data/users/chernikava/fbsource/fbcode/biggrep (746381e21)]$ xbgf "\.(h\+\+|hh)$" --count
6872 hits for this query
```
Lets add them to the list :)

Impact: unknown

Reviewed By: chatura-atapattu

Differential Revision: D49741220

fbshipit-source-id: 5d2813a5a63ec03982fcca0aa8ea96b646cb4c38