error: `Category::Combine`
Summary:
For next diff

Using `PartialOrd` for this is kind of a hack, but it'll make this "just work" if we add a third variant which is nice I guess

Reviewed By: stepancheg

Differential Revision: D53605117

fbshipit-source-id: 72bad48a8270ddb9f64d1b5b718ed68f4655068e