buck2_error: Remove `#[from]` usage
Summary: New implementation doesn't support it anymore

Reviewed By: stepancheg, iguridi

Differential Revision: D51453172

fbshipit-source-id: 1fad78fb7e562613802f7e84b5bf12dd0df8becd