Fix unused import in buck2_execute_impl
Summary:
```lang=log,counterexample
error: unused import: `host_sharing::NamedSemaphores`
  --> app/buck2_execute_impl/src/executors/worker.rs:56:5
   |
56 | use host_sharing::NamedSemaphores;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: requested on the command line with `-D unused-imports`
```

Reviewed By: diliop

Differential Revision: D92583243

fbshipit-source-id: 226d48eb50ffe9df0fc3c0443e510fcb7125b3f9