buck2_error: Introduce late format concept
Summary:
Explained in doc comment.

We only need this for action errors for now, so we'll just require explicitly constructing with a special constructor for now. In the general case these kinds of things should be made part of the derive macro

Reviewed By: wendy728

Differential Revision: D50213707

fbshipit-source-id: 8c903688962327a3889647d3f7725c21f3520d83