Polish bootstrapping steps
Summary:
Bizarrely, `cargo install --git https://github.com/facebookincubator/reindeer` works on macOS but not on Linux nor Windows.

On Linux in GitHub Actions it fails with:

```
    Updating git repository `https://github.com/facebookincubator/reindeer`
warning: skipping duplicate package `rust-third-party` found at `/home/runner/.cargo/git/checkouts/reindeer-c03e7d4c9f50fdff/1ee2a81/test/with_fixups`
warning: skipping duplicate package `rust-third-party` found at `/home/runner/.cargo/git/checkouts/reindeer-c03e7d4c9f50fdff/1ee2a81/test/extramissingmeta`
warning: skipping duplicate package `rust-third-party` found at `/home/runner/.cargo/git/checkouts/reindeer-c03e7d4c9f50fdff/1ee2a81/test/base`
error: multiple packages with binaries found: reindeer, rust-third-party. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```

Same thing on Windows in GitHub Actions:

```
    Updating git repository `https://github.com/facebookincubator/reindeer`
warning: skipping duplicate package `rust-third-party` found at `C:\Users\runneradmin\.cargo\git\checkouts\reindeer-c03e7d4c9f50fdff\1ee2a81\test\base`
warning: skipping duplicate package `rust-third-party` found at `C:\Users\runneradmin\.cargo\git\checkouts\reindeer-c03e7d4c9f50fdff\1ee2a81\test\extramissingmeta`
warning: skipping duplicate package `rust-third-party` found at `C:\Users\runneradmin\.cargo\git\checkouts\reindeer-c03e7d4c9f50fdff\1ee2a81\test\with_fixups`
error: multiple packages with binaries found: reindeer, rust-third-party. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```

 ---

Separately I fixed reindeer.toml to produce output in the correct location. The current use of `file_name = "BUILD"` in buck2's reindeer.toml is from:

- {D42384802} (January)

which is significantly older than the following developments:

- {D43599417} (February)
- {D43599418} (February)
- {D43534148} (February)

Reviewed By: zertosh

Differential Revision: D45646690

fbshipit-source-id: 785bfb2432d444d94f9f974e537d1323aa168dac