buck2_error: Refactor top-level logic a bit
Summary: Make the main impl method return a `Result`, so that we can use `?`

Reviewed By: stepancheg

Differential Revision: D50934104

fbshipit-source-id: 81c403b26cb77e2bd6e351d8bb35779df4d588a6