buck2_error: Add `AsDynError`
Summary: This is needed to make thiserror compatibility with `anyhow` work (via deref specialization tricks). We do use that in two places and it seems easier to just keep than have to do workarounds elsewhere

Reviewed By: stepancheg

Differential Revision: D51453180

fbshipit-source-id: d9b29a703806ae8292e438b4015567f9e3b65a92