buck2_error: Extract some logic into a function
Summary: So that it's easier to change next diff

Reviewed By: wendy728

Differential Revision: D51057841

fbshipit-source-id: 659b171dea892ea9bff7063f88988ba1ac1bd00d