Ignore errors and diagnostics when building index stores
Summary:
We've been failing to build saved state directories that include the igios target (specifically 'all' and 'instagram-ios') since the 14th of July when D77881689 landed. Example sandcastle job with failure: https://www.internalfb.com/sandcastle/workflow/3805541685137098856

```
$ buck build 'fbsource//fbobjc/Libraries/Optic:OpticHardwareSession[index-store]'
fbobjc/Libraries/Optic/OpticHardwareSession/modifier/OpticHardwareDeviceCinematicModeModifier.swift:27:19: error: cannot find user version number for module 'Foundation'; version number ignored
25 |       return
26 |     }
27 |     #if canImport(Foundation, _version: 4030.1.101)
   |                   `- error: cannot find user version number for module 'Foundation'; version number ignored
```

This looks like an issue with the index-store subtarget not being able to see the Foundation version, which we should fix. Normal builds are succeeding.

However, we want index-store to always succeed, so we can always generate an index store directory with content even if a few files have errors in them. This was implemented in D72272866, but D76902242 (introducing serialized diagnostics) meant that build failures stop index-store succeeding again.

Instead, ensure index-store always creates directories for both object files and index store files, and always ignore errors.

Reviewed By: rmaz

Differential Revision: D78823498

fbshipit-source-id: fc71bfde858703eed00dc602103a659cf05df4f5