buck2_error: Better support for generic errors
Summary: Just adds enough bounds to the impl so that it gets correctly ignored if the generics mean that `Send` or `Sync` or whatever bounds wouldn't be satisfied

Reviewed By: stepancheg

Differential Revision: D50934110

fbshipit-source-id: 7d06bd939a89c77528afe5bee397f9a4ae97c435