fix oss windows CI breakage from memory reporter
Summary:
github cargo builds on Windows broke:
```
error: calls to `std::mem::drop` with a value that implements `Copy` does nothing
   --> app\buck2_server\src\daemon\server.rs:491:21
    |
491 |                     drop(memory_reporter);
    |                     ^^^^^---------------^
    |                          |
    |                          argument has type `std::option::Option<bool>`
    |
    = note: requested on the command line with `-D dropping-copy-types`
```

Reviewed By: Will-MingLun-Li

Differential Revision: D81162448

fbshipit-source-id: d3b800a369d0a2be1f1f4336a30ff63f06352ecf