Make rustc_flags=["-g"] not break rustdoc
Summary:
D41773002 (https://github.com/facebookincubator/buck2/commit/222ce4cf5b4e050c46a74750434f500dce129106) broke documentation of targets that use "-g" in their `rustc_flags`.

https://www.internalfb.com/code/fbsource/[57e1d511f05e0e9d036493db003b74c275e7879b]/fbcode/hphp/hack/src/typing/TARGETS?lines=714-715%2C728-731%2C741

```
Action failed: fbcode//hphp/hack/src/typing:typing_defs_rust (rustdoc)
Local command returned non-zero exit code 1
Reproduce locally: `/usr/bin/env "PYTHONPATH=buck-out/v2/gen/prelude/9dbbb55f355c29b9/rust/tools/__rustc_action__/__rust ...<omitted>... ed:oxidized" "--extern-html-root-url=oxidized_by_ref=/hphp/hack/src/oxidized_by_ref:oxidized_by_ref" (rerun your previous command with -v2 to view the untruncated command)`
stdout:
stderr:
error: Unrecognized option: 'g'

BUILD FAILED
Failed to build 'fbcode//hphp/hack/src/typing:typing_defs_rust (ovr_config//platform/linux:x86_64-fbcode-platform010-clang-882bd00a4ffb1e1d)'
```

The need to use `if str(flag) == '"-g"'` (instead of the obvious `flag == "-g"`) is unfortunate. See https://fb.workplace.com/groups/buck2users/posts/2919545654968463; for rule attrs that arrive into the prelude by way of an `attrs.arg()`, there is currently no way to inspect their value as an ordinary starlark string.

https://www.internalfb.com/code/fbsource/[0fe9511eef2a0c0aa0fb4ded36fb37fc68ae5679]/fbcode/buck2/prelude/attributes.bzl?lines=2677

Sadly we already have a similar workaround when dealing with clippy-related flags from the buckconfig, for the same reason:

https://www.internalfb.com/code/fbsource/[1cc854ac8f72c6bbde4e0a693840d06480720596]/fbcode/buck2/prelude/rust/build.bzl?lines=401-402

Reviewed By: zertosh

Differential Revision: D41858724

fbshipit-source-id: cb50133121ea10c5eb01815e621afff6a0e3117d