Re-commit D57889230
Summary:
A second attempt at fixing the duplicate member bug in dist_lto_prepare.py. Original diff: D57889230. In
the previous attempt to land, adfinder and some other important builds broke.

The previous attempt failed because we used os.rename to rename a file between
file systems: https://www.internalfb.com/sandcastle/workflow/3265109729846704586

```
File "/re_cwd/buck-out/v2/gen/prelude/898ad24bd92b3725/cxx/dist_lto/tools/__dist_lto_prepare__/dist_lto_prepare.py", line 130, in main
    os.rename(
OSError: [Errno 18] Invalid cross-device link: '/re_tmp/tmpefr1sgsc/cpu.o' -> '/re_cwd/buck-out/v2/gen/fbcode/af046fc34ed1558a/admarket/adfinder/__adfinder_hottext__/thin_lto_prepare_executable/avutil/lib/libavutil.a/objects/cpu.o'
```

The docs specify to use `shutil.move` in this case, so that's what I've done in the second attempt:

> The operation may fail if src and dst are on different filesystems. Use shutil.move() to support moves to a different filesystem.

https://docs.python.org/3/library/os.html#os.rename

#buildmore

Reviewed By: kyulee-com

Differential Revision: D58110917

fbshipit-source-id: 1f80bea25f741702444a302c8d87b481c36685c2