Allowlist some duplicate so
Summary:
Temporary workaround for this error in D75248850: P1831339201

```
AssertionError: Duplicate library name: libxplat_cdn_cache_key_cache_key_thrift-cpp2-typesAndroid.so! Source1: /data/users/dchornyi/fbsource/buck-out/v2/gen/wa_android/a812f74a786a2559/libraries/pando/__pando_aar__/jni/arm64-v8a/libxplat_cdn_cache_key_cache_key_thrift-cpp2-typesAndroid.so, source2: buck-out/v2/gen/wa_android/24f5f405948d7847/app/whatsapp/__wa_debug_aab__/__action___0__/stripped_native_linkables/arm64-v8a/libxplat_cdn_cache_key_cache_key_thrift-cpp2-typesAndroid.so
```

**Context**
`wa_android//app/whatsapp:compress_native` superpacks native code during WA Android build. Input into superpacking are targets that are explicitly listed in [superpack_allowlist.bzl](http://internalfb.com/code/fbsource/[eff8a0223f0f]/whatsapp/android/app/infra/superpack/tools/resources/superpack_allowlist.bzl).

While doing Pando Live migration, in D74919595 we first tried to switch each Pando `*.so` file from `wa_android//libraries/bloks/libs/maven:pando` to individual FBS targets that build these *.sos. Although this works, the  immediate result was +800KB in [BSB](https://fburl.com/diff/uy6psxoy). In D75177937 (later integrated into D75248850) this approach was replaced by "proxying" Pando `*.so` through the `wa_android//libraries/pando:pando_aar` which calls the same target `fbsource//fbandroid/libraries/wabloks:pando_native` as Bloksync does, except it's done "live" during the WA Android build. This way we still leverage the same [merge maps](https://fburl.com/code/ok1v71qv) that Bloksync build uses and so the binary size remains unchanged.

The problem is that outside of `wa_android//app/whatsapp:compress_native` some targets transitively reference the same FBS *.so targets and we end up in a situation where the same *.so is provided by `wa_android//libraries/pando:pando_aar` and the actual FBS target.

This diff allowlists such `*.so` files, unblocking the Pando live migration. This is intended to be a temporary solution until a more robust `*.so` linking/merging strategy for WA Android is adopted (e.g., using the FBS [somerge](https://www.internalfb.com/wiki/Android_Native_Library_Merging/) tooling).

Differential Revision: D75773660

fbshipit-source-id: 7d290f7d44bd35f58eedb69a0034f32f61a8656b