Explicitly use Android toolchain for Buck Android tests
Summary:
With JDK 21:

```
$ buck build prelude//toolchains/android/test/com/facebook/buck/jvm/java:java

Action failed: prelude//toolchains/android/test/com/facebook/buck/jvm/java:java (cfg:dev-linux-x86_64-fbcode-platform010-clang19-asan-ubsan-dev#aa62b4b046685d46) (javac_and_jar)
Local command returned non-zero exit code 2
Local command: env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/prelude/3837421b2634d6e0/javac_and_jar' /usr/local/fbcode/platform010/bin/python3.12 buck-out/v2/gen/prelude/e9ab0fde28433431/java/tools/__compile_and_package__/__compile_and_package__/compile_and_package.py --jar_builder_tool 'buck-out/v2/gen/fbcode/e9ab0fde28433431/tools/build/buck/wrappers/__java17.sh__/java17.sh -jar buck-out/v2/gen/prelude/e9ab0fde28433431/toolchains/android/src/com/facebook/buck/util/zip/__jar_builder_prebuilt__/symlink/jar_builder_main.jar' --output buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/jar/java.jar --javac_tool buck-out/v2/gen/fbcode/e9ab0fde28433431/tools/build/buck/wrappers/__javac17.sh__/javac17.sh --javac_classpath_file buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/classpath_args --generated_sources_dir buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/generated_sources --javac_args_file buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/javac_args
Stdout: <empty>
Stderr:
[compile_and_package.py] [debug] javac_tool: buck-out/v2/gen/fbcode/e9ab0fde28433431/tools/build/buck/wrappers/__javac17.sh__/javac17.sh
[compile_and_package.py] [debug] jar_builder_tool: buck-out/v2/gen/fbcode/e9ab0fde28433431/tools/build/buck/wrappers/__java17.sh__/java17.sh -jar buck-out/v2/gen/prelude/e9ab0fde28433431/toolchains/android/src/com/facebook/buck/util/zip/__jar_builder_prebuilt__/symlink/jar_builder_main.jar
[compile_and_package.py] [debug] output: buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/jar/java.jar
[compile_and_package.py] [debug] javac_args: buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/javac_args
[compile_and_package.py] [debug] javac_classpath: buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/classpath_args
[compile_and_package.py] [debug] generated_sources_dir: buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/generated_sources
[compile_and_package.py] [debug] executing command = 'buck-out/v2/gen/fbcode/e9ab0fde28433431/tools/build/buck/wrappers/__javac17.sh__/javac17.sh buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/javac_args -classpath buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/classpath_args -s buck-out/v2/gen/prelude/aa62b4b046685d46/toolchains/android/test/com/facebook/buck/jvm/java/__java__/generated_sources -g -d /data/sandcastle/boxes/trunk-hg-full-fbsource/buck-out/v2/tmp/prelude/3837421b2634d6e0/javac_and_jar/tmpf68w22m8/classes'
error: invalid source release: 21
Usage: javac <options> <source files>
use --help for a list of possible options
```

The wrong Java version is used (should use 21, but 17 is used).

Reviewed By: jselbo

Differential Revision: D80973202

fbshipit-source-id: c783c8122e9f757736902c631f913b2fc2940680