buck2_error: Simplify type in error root
Summary: Instead of storing a `Marc<anyhow::Error>` just store a string. This makes it clear in the type that there are no further sources hiding behind the root

Reviewed By: stepancheg

Differential Revision: D52022072

fbshipit-source-id: bbdca23510c641f7234c3eb1b79d02395eed55c5