Fix macos_transition missing sdk constraint
Summary:
Optionally check for sdk constraint because it may not exist and fail with
```
    1: Error computing transition `prelude//apple/user/macos_transition.bzl#macos_transition (cfg:iphoneos#067d6f847ee19eb8)`
    2: Traceback (most recent call last):
         File <builtin>, in <module>
       error: Key `ovr_config//os/sdk/apple/constraints:_` was not found
         --> fbcode/buck2/prelude/apple/user/macos_transition.bzl:27:20
          |
       27 |     is_sdk_macos = platform.configuration.constraints[constraint_sdk.label] == refs.sdk_macos[ConstraintValueInfo]
          |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |
```

Differential Revision: D72054690

fbshipit-source-id: c2e7998fbde4b5855d04396093dad6bf3d429b1c