add config flag to bxl script for swift index store
Summary:
Due to current issues with the pika 17 rollout plan, there seems to be an issue where its using some things from xcode16.4 but also pika 16.3, which I believe could have issues. The error messages in the logs indicate we are using some xcode16.4 but also pika 16.3, which most likely is causing these conflicting issues. Add in an optional flag for the buck command so that we can pass in the toolchain version.

e.g.
```
buck-out/v2/gen/fbsource/a9582032d7752f86/xplat/toolchains/apple/__xcode_16.4.0_16f6-iphonesimulator-sdk_genrule-actual__/iPhoneSimulator18.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:87:54: note: 'shared' has been explicitly marked unavailable here
 85 | interface UIApplication : UIResponder
 86 |
 87 | property(class, nonatomic, readonly) UIApplication *sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
    |                                                      `- note: 'shared' has been explicitly marked unavailable here
 88 |
 89 | property(nullable, nonatomic, assign) id<UIApplicationDelegate> delegate;
Failed to open diagnostics fileTraceback (most recent call last):
  File "/re_cwd/buck-out/v2/gen/prelude/72700902c6a8c8e8/apple/tools/__swift_exec__/__swift_exec__/swift_exec.py", line 373, in <module>
    main()
  File "/re_cwd/buck-out/v2/gen/prelude/72700902c6a8c8e8/apple/tools/__swift_exec__/__swift_exec__/swift_exec.py", line 291, in main
    subprocess.run(
  File "/usr/local/fbcode/platform010/lib/python3.12/subprocess.py", line 573, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['buck-out/v2/gen/fbsource/72700902c6a8c8e8/xplat/toolchains/facebook-dt/tools/__pika-16.3_serialized-diags-to-json_noasserts_fat__/__command_alias_trampoline.sh', 'buck-out/v2/gen/fbsource/be8eaab357179969/fbobjc/Apps/Instagram/Features/Shopping/IGUnifiedTagsListKit/__IGUnifiedTagsListSwift__/__diagnostics__/swift_index_compile.json.dia']' returned non-zero exit status 1.
```

Some additional guidance here:
https://fb.workplace.com/groups/iOSAppChampions/posts/24375703835370457/?comment_id=24403344175939756&reply_comment_id=24404148029192704

Specifically:
```
Champions should still be able to specify both the apple.xcode_sdk_version  pointing to Xcode 26b1 and apple.version=pika-17-staging to keep trying locally. Xcodestaging builds do that automatically.
```
hence, using `pika-17-staging`.

Differential Revision: D77171947

fbshipit-source-id: a48b7f9ec272f12a9519e6811a6f8ead00f2b3d7