buck2: add some lifetime annotations
Summary:
I'm transiently getting errors while compiling:

```
error[E0621]: explicit lifetime required in the type of `working_dir`
   --> buck2_build_api/src/query/dice/mod.rs:372:44
    |
369 |       working_dir: &ProjectRelativePath,
    |                    -------------------- help: add explicit lifetime `'c` to the type of `working_dir`: `&'c buck2_core::fs::project::ProjectRelativePath`
...
372 |   ) -> anyhow::Result<DiceQueryDelegate<'c>> {
    |  ____________________________________________^
373 | |     let cell_resolver = ctx.get_cell_resolver().await?;
374 | |     let package_boundary_exceptions = ctx.get_package_boundary_exceptions().await?;
375 | |     let target_alias_resolver = ctx
...   |
386 | |     )
387 | | }
    | |_^ lifetime `'c` required
```

This seems incorrect but this looks like this change gets things to work and
it doesn't hurt.

Reviewed By: ndmitchell

Differential Revision: D38908664

fbshipit-source-id: a971fd191348e757894fe8310bf47bc4d7ed1306