Ignore directories that should not be parsed as part of project
Summary:
These directories break `buck2 utargets ...`.

```lang=text,counterexample
Error parsing gh_facebook_buck2//examples/bootstrap/bootstrap/platform
Error evaluating build file: `gh_facebook_buck2//examples/bootstrap/bootstrap/platform:BUCK`

Caused by:
    0: Traceback (most recent call last):
         * examples/bootstrap/bootstrap/platform/BUCK:12, in <module>
             platform(

       error: Error coercing attribute `constraint_values` of `gh_facebook_buck2//examples/bootstrap/bootstrap/platform:bootstrap`
         --> examples/bootstrap/bootstrap/platform/BUCK:12:1
          |
       12 | / platform(
       13 | |     name = "bootstrap",
       14 | |     constraint_values = ["bootstrap//:use_bootstrap"],
       15 | |     visibility = ["PUBLIC"],
       16 | |     deps = [":default"],
       17 | | )
          | |_^
          |
    1: Error coercing attribute `constraint_values` of type `attrs.list(attrs.dep(), default=[])`
    2: Error coercing ["bootstrap//:use_bootstrap"]
    3: Error coercing "bootstrap//:use_bootstrap"
    4: Invalid target pattern `bootstrap//:use_bootstrap` is not allowed
    5: unknown cell alias: `bootstrap`. In cell `gh_facebook_buck2`, known aliases are: `fbsource, fbcode_macros, prelude, gh_facebook_buck2, fbcode, config, gh_facebook_buck2_shims_meta, toolchains, none, ovr_config, bazel_skylib, root, buck, shim`
```

```lang=text,counterexample
Error parsing gh_facebook_buck2//integrations/rust-project/tests
From load at integrations/rust-project/tests/BUCK:1

Caused by:
    File not found: `gh_facebook_buck2_shims_meta//buck2/tests/buck_e2e.bzl`
```

```lang=text,counterexample
Error parsing gh_facebook_buck2//tests/core/analysis
From load at tests/core/analysis/BUCK:1

Caused by:
    File not found: `gh_facebook_buck2_shims_meta//buck2/tests/buck_e2e.bzl`
```

Reviewed By: JakobDegen

Differential Revision: D74543459

fbshipit-source-id: bee3277f097ab0972133d0afabe15b6f691cb78a