buck2_error: Simplify context reconstruction
Summary: Easier, now that we don't need to be preserving the types behind the `dyn Error`s anymore

Reviewed By: iguridi

Differential Revision: D52022073

fbshipit-source-id: 07194c8835044f1e0cdecf6ea03a3912201c9aa1