Improving Mockingbird Error On Objc Only Modules
Summary:
If you try to add mockingbird mocks for a module with no swift files in it you get a confusing error about the MockingLibraryInfo not being there.

```
Error running analysis for `waios//Tests/MessagingInfraTests:MessagingInfraTests (wa_config//platform:consumer-iphonesimulator-arm64-debug#47e03e59be9b7c55)`

Caused by:
    0: Error running analysis for `waios//modules/WAMessagingInfraPlatformAPIs:WAMessagingInfraPlatformAPIsMocks (wa_config//platform:consumer-iphonesimulator-arm64-debug-enable-testing#20c3e63a0c6d1a86)`
    1: Traceback (most recent call last):
         File <builtin>, in <module>
       error: Error accessing dependencies of `waios//modules/WAMessagingInfraPlatformAPIs:WAMessagingInfraPlatformAPIs (wa_config//platform:consumer-iphonesimulator-arm64-debug-enable-testing#20c3e63a0c6d1a86)`
         --> tools/buck2/prelude/apple/mockingbird/mockingbird_mock.bzl:13:24
          |
       13 |     mockingbird_info = ctx.attrs.module[MockingbirdLibraryInfo]
          |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |

    2: provider collection does not have a key `MockingbirdLibraryInfo`, available keys are: [`CxxExportedNeedsCoverageInstrumentation`, `CxxCompilationDbInfo`, `LinkCommandDebugOutputInfo`, `LinkExecutionPreferenceInfo`, `ResourceGraphInfo`, `AppleLibraryInfo`, `UnstrippedLinkOutputInfo`, `XcodeDataInfo`, `MergedLinkInfo`, `SharedLibraryInfo`, `UnixEnvInfo`, `CPreprocessorInfo`, `IndexStoreInfo`, `LinkableGraph`, `ResourceInfo`, `TemplatePlaceholderInfo`, `DefaultInfo`, `LinkGroupLibInfo`, `SwiftPCMUncompiledInfo`, `SwiftDependencyInfo`, `XCTestSwiftSupportInfo`]
1 BUILDS FAILED
```

It's expected that mockingbird won't generate anything for these modules as it only generates code for swift.

Improving the error message to make it clear what's wrong.

Differential Revision: D65655250

fbshipit-source-id: afdf3251e9625064ba71869cf5eb2b77ee512adb