Fix broken use of buck2_core::env_helper
Summary:
Broken by a race between {D51778936} (which renamed `buck2_core::env_helper` to `buck2_core::env::helper`) and {D51386428} (wihch added a use of `buck2_core::env_helper`).

```
error[E0432]: unresolved import `buck2_core::env_helper`
  --> fbcode/buck2/app/buck2_execute/src/execute/cache_uploader.rs:12:17
   |
12 | use buck2_core::env_helper::EnvHelper;
   |                 ^^^^^^^^^^ could  not find `env_helper` in `buck2_core`
```

Reviewed By: iguridi

Differential Revision: D51783728

fbshipit-source-id: 2907674124eef3b3eb8e1a8a6eed01aae4905208