Fix conflicting proto field id
Summary:
`101` is already used by `sink_bytes_written` in the same type, so changing `active_networks_kinds` to `102`.

This was causing:

```
Error: Custom { kind: Other, error: "protoc failed: data.proto:2017:48: Field number 101 has already been used in \"buck.data.InvocationRecord\" by field \"sink_bytes_written\".\n" }
```

Reviewed By: Will-MingLun-Li

Differential Revision: D62526140

fbshipit-source-id: 5e5ad5529c9ff8beeb10460bbe441ff4d959fd97