Enable lalrpop's pico-args dependency as required by its bin crate
Summary:
This reverts D45407769 and fixes the *"error: can't find crate for `pico_args`"* error in what I claim is a better way.

The `lalrpop` package contains this binary crate:

```
[package]
name = "lalrpop"
version = "0.19.12"
...

[dependencies]
pico-args = { version = "0.4", default_features = false, optional = true }
...

[[bin]]
name = "lalrpop"
required-features = ["pico-args"]
```

Per the `required-features`, It requires you to enable the "pico-args" feature if you want to build the lalrpop binary.

One would hope that Cargo could recognize this `required-features` and automatically enabled the required feature(s) in the case of an artifact dependency on that binary, but this is not the case. I opened a Cargo bug about this.

When you build just the binary directly, as opposed to through an artifact dependency, Cargo does catch if you're missing the required feature.

```
$ cargo check --bin lalrpop
error: target `lalrpop` in package `lalrpop` requires the features: `pico-args`
Consider enabling them by passing, e.g., `--features="pico-args"`
```

Reviewed By: themarwhal

Differential Revision: D45428024

fbshipit-source-id: b0b769fe4e2b37a61d83e8c5146c99d6722f454d