Make attrs.tuple() resolve_single() on children
Previously if you used attrs.tuple(attrs.source(), ...), then a label
that resolved to multiple default_outputs would cause the tuple to have
more elements than declared. For example, where `:multi_output` has
two outputs one and two.cpp:

cxx_library(
    ...
    srcs = [ (":multi_output", ["-Wall"]) ],
)

    error: Value `<source scratch/two.cpp>` of type `artifact` does not match the type annotation `list[resolved_macro]` for argument `flags`
--> prelude/cxx/cxx_sources.bzl:42:47
       |
    42 |             cxx_src_with_flags_records.append(CxxSrcWithFlags(file = artifact, flags = flags, index = index))
       |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |

After this change, the error is better (but still needs some context):

Caused by:
    Expected a single artifact from root//scratch:multi_output (platforms//:host#9f5b0576f0e10a13), but it returned 2 artifacts