Add starlark span to invalid load errors
Before:

    BUILD FAILED
    Error loading `load` of `abc` from `BUCK:5:6-11`

    Caused by:
        Import path must have suffix `.bzl`: `gh_facebook_buck2//abc`

After:

    BUILD FAILED

    error: Error loading `load` of `abc`
     --> BUCK:5:6
      |
    5 | load("abc", "def")
      |      ^^^^^
      |

    Caused by:
        Import path must have suffix `.bzl`: `gh_facebook_buck2//abc`