buck2_error: Introduce `UniqueRootId`
Summary: A type that uniquely identifies an error root. We'll use this for error deduplication

Reviewed By: wendy728

Differential Revision: D50397278

fbshipit-source-id: eacb594513d24f418b808ff09653730e36104193