Disable broken test coverage tests
Summary:
The [test](https://www.internalfb.com/intern/sandcastle/job/799564941/insights) is currently failing on master with the following message, let's disable so that `buck2` job is green again.

Repro command

```
buck2 test fbcode//buck2/tests/e2e:test_buck_test -- test_cpp_test_coverage
```

Bisect leads to D40382059

Error on master

```
[2022-10-17T04:11:28.092-07:00] ✗ Fail: buck2/tests/e2e:test_buck_test - test_buck_test.py::test_cpp_test_coverage (13.1s)
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /usr/local/fbcode/platform010/bin/python3.8
rootdir: /data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource
plugins: asyncio-0.16.0
collecting ... collected 1 item

../buck-out/v2/gen/fbcode/110b607930331a92/buck2/tests/e2e/__test_buck_test__/test_buck_test#link-tree/buck2/tests/e2e/test_buck_test.py::test_cpp_test_coverage FAILED

=================================== FAILURES ===================================
____________________________ test_cpp_test_coverage ____________________________
Traceback (most recent call last):
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/110b607930331a92/buck2/tests/e2e/__test_buck_test__/test_buck_test#link-tree/buck2/tests/e2e/test_buck_test.py", line 89, in test_cpp_test_coverage
    assert "fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp" in paths, str(
AssertionError: ['./fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp', './fbcode/common/base/BuildInfo-extras.cpp', './fbcode/common/base/InitRegistry.cpp', './fbcode/common/gtest/LightMain.cpp', './fbcode/common/init/InitState.cpp', './fbcode/common/init/Kill.cpp', './fbcode/common/init/light.cpp', './fbcode/common/logging/logging_impl.cpp', './fbcode/common/memory/OperatorOverride.cpp', './fbcode/folly/CancellationToken.cpp', './fbcode/folly/Conv.cpp', './fbcode/folly/Demangle.cpp', './fbcode/folly/ExceptionString.cpp', './fbcode/folly/Executor.cpp', './fbcode/folly/File.cpp', './fbcode/folly/FileUtil.cpp', './fbcode/folly/Format.cpp', './fbcode/folly/ScopeGuard.cpp', './fbcode/folly/SharedMutex.cpp', './fbcode/folly/Singleton.cpp', './fbcode/folly/String.cpp', './fbcode/folly/Unicode.cpp', './fbcode/folly/concurrency/CacheLocality.cpp', './fbcode/folly/container/detail/F14Table.cpp', './fbcode/folly/detail/AsyncTrace.cpp', './fbcode/folly/detail/Futex.cpp', './fbcode/folly/detail/MemoryIdler.cpp', './fbcode/folly/detail/StaticSingletonManager.cpp', './fbcode/folly/detail/ThreadLocalDetail.cpp', './fbcode/folly/detail/UniqueInstance.cpp', './fbcode/folly/dynamic.cpp', './fbcode/folly/executors/CPUThreadPoolExecutor.cpp', './fbcode/folly/executors/GlobalThreadPoolList.cpp', './fbcode/folly/executors/QueueObserver.cpp', './fbcode/folly/executors/QueuedImmediateExecutor.cpp', './fbcode/folly/executors/ThreadPoolExecutor.cpp', './fbcode/folly/experimental/symbolizer/Dwarf.cpp', './fbcode/folly/experimental/symbolizer/DwarfImpl.cpp', './fbcode/folly/experimental/symbolizer/DwarfLineNumberVM.cpp', './fbcode/folly/experimental/symbolizer/DwarfSection.cpp', './fbcode/folly/experimental/symbolizer/DwarfUtil.cpp', './fbcode/folly/experimental/symbolizer/Elf.cpp', './fbcode/folly/experimental/symbolizer/ElfCache.cpp', './fbcode/folly/experimental/symbolizer/SignalHandler.cpp', './fbcode/folly/experimental/symbolizer/StackTrace.cpp', './fbcode/folly/experimental/symbolizer/SymbolizePrinter.cpp', './fbcode/folly/experimental/symbolizer/SymbolizedFrame.cpp', './fbcode/folly/experimental/symbolizer/Symbolizer.cpp', './fbcode/folly/hash/SpookyHashV2.cpp', './fbcode/folly/init/Init.cpp', './fbcode/folly/init/Phase.cpp', './fbcode/folly/io/IOBuf.cpp', './fbcode/folly/io/async/Request.cpp', './fbcode/folly/json.cpp', './fbcode/folly/json_pointer.cpp', './fbcode/folly/lang/CString.cpp', './fbcode/folly/lang/Exception.cpp', './fbcode/folly/lang/SafeAssert.cpp', './fbcode/folly/logging/AsyncFileWriter.cpp', './fbcode/folly/logging/AsyncLogWriter.cpp', './fbcode/folly/logging/CustomLogFormatter.cpp', './fbcode/folly/logging/FileWriterFactory.cpp', './fbcode/folly/logging/GlogStyleFormatter.cpp', './fbcode/folly/logging/ImmediateFileWriter.cpp', './fbcode/folly/logging/Init.cpp', './fbcode/folly/logging/InitWeak.cpp', './fbcode/folly/logging/LogCategory.cpp', './fbcode/folly/logging/LogCategoryConfig.cpp', './fbcode/folly/logging/LogConfig.cpp', './fbcode/folly/logging/LogConfigParser.cpp', './fbcode/folly/logging/LogHandlerConfig.cpp', './fbcode/folly/logging/LogLevel.cpp', './fbcode/folly/logging/LogMessage.cpp', './fbcode/folly/logging/LogName.cpp', './fbcode/folly/logging/LoggerDB.cpp', './fbcode/folly/logging/RateLimiter.cpp', './fbcode/folly/logging/StandardLogHandler.cpp', './fbcode/folly/logging/StandardLogHandlerFactory.cpp', './fbcode/folly/logging/StreamHandlerFactory.cpp', './fbcode/folly/memory/MallctlHelper.cpp', './fbcode/folly/memory/ReentrantAllocator.cpp', './fbcode/folly/net/NetOps.cpp', './fbcode/folly/portability/SysMembarrier.cpp', './fbcode/folly/synchronization/AsymmetricThreadFence.cpp', './fbcode/folly/synchronization/Hazptr.cpp', './fbcode/folly/synchronization/HazptrThreadPoolExecutor.cpp', './fbcode/folly/synchronization/ParkingLot.cpp', './fbcode/folly/system/AtFork.cpp', './fbcode/folly/system/ThreadId.cpp', './fbcode/folly/system/ThreadName.cpp', './fbcode/folly/tracing/AsyncStack.cpp']
assert 'fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp' in ['./fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp', './fbcode/common/base/BuildInfo-extras.cpp', './fbcode/co...pp', './fbcode/common/gtest/LightMain.cpp', './fbcode/common/init/InitState.cpp', './fbcode/common/init/Kill.cpp', ...]
=========================== short test summary info ============================
FAILED ../buck-out/v2/gen/fbcode/110b607930331a92/buck2/tests/e2e/__test_buck_test__/test_buck_test#link-tree/buck2/tests/e2e/test_buck_test.py::test_cpp_test_coverage
============================== 1 failed in 13.11s ==============================

Traceback (most recent call last):
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/110b607930331a92/buck2/tests/e2e/__test_buck_test__/test_buck_test#link-tree/buck2/tests/e2e/test_buck_test.py", line 89, in test_cpp_test_coverage
    assert "fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp" in paths, str(
AssertionError: ['./fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp', './fbcode/common/base/BuildInfo-extras.cpp', './fbcode/common/base/InitRegistry.cpp', './fbcode/common/gtest/LightMain.cpp', './fbcode/common/init/InitState.cpp', './fbcode/common/init/Kill.cpp', './fbcode/common/init/light.cpp', './fbcode/common/logging/logging_impl.cpp', './fbcode/common/memory/OperatorOverride.cpp', './fbcode/folly/CancellationToken.cpp', './fbcode/folly/Conv.cpp', './fbcode/folly/Demangle.cpp', './fbcode/folly/ExceptionString.cpp', './fbcode/folly/Executor.cpp', './fbcode/folly/File.cpp', './fbcode/folly/FileUtil.cpp', './fbcode/folly/Format.cpp', './fbcode/folly/ScopeGuard.cpp', './fbcode/folly/SharedMutex.cpp', './fbcode/folly/Singleton.cpp', './fbcode/folly/String.cpp', './fbcode/folly/Unicode.cpp', './fbcode/folly/concurrency/CacheLocality.cpp', './fbcode/folly/container/detail/F14Table.cpp', './fbcode/folly/detail/AsyncTrace.cpp', './fbcode/folly/detail/Futex.cpp', './fbcode/folly/detail/MemoryIdler.cpp', './fbcode/folly/detail/StaticSingletonManager.cpp', './fbcode/folly/detail/ThreadLocalDetail.cpp', './fbcode/folly/detail/UniqueInstance.cpp', './fbcode/folly/dynamic.cpp', './fbcode/folly/executors/CPUThreadPoolExecutor.cpp', './fbcode/folly/executors/GlobalThreadPoolList.cpp', './fbcode/folly/executors/QueueObserver.cpp', './fbcode/folly/executors/QueuedImmediateExecutor.cpp', './fbcode/folly/executors/ThreadPoolExecutor.cpp', './fbcode/folly/experimental/symbolizer/Dwarf.cpp', './fbcode/folly/experimental/symbolizer/DwarfImpl.cpp', './fbcode/folly/experimental/symbolizer/DwarfLineNumberVM.cpp', './fbcode/folly/experimental/symbolizer/DwarfSection.cpp', './fbcode/folly/experimental/symbolizer/DwarfUtil.cpp', './fbcode/folly/experimental/symbolizer/Elf.cpp', './fbcode/folly/experimental/symbolizer/ElfCache.cpp', './fbcode/folly/experimental/symbolizer/SignalHandler.cpp', './fbcode/folly/experimental/symbolizer/StackTrace.cpp', './fbcode/folly/experimental/symbolizer/SymbolizePrinter.cpp', './fbcode/folly/experimental/symbolizer/SymbolizedFrame.cpp', './fbcode/folly/experimental/symbolizer/Symbolizer.cpp', './fbcode/folly/hash/SpookyHashV2.cpp', './fbcode/folly/init/Init.cpp', './fbcode/folly/init/Phase.cpp', './fbcode/folly/io/IOBuf.cpp', './fbcode/folly/io/async/Request.cpp', './fbcode/folly/json.cpp', './fbcode/folly/json_pointer.cpp', './fbcode/folly/lang/CString.cpp', './fbcode/folly/lang/Exception.cpp', './fbcode/folly/lang/SafeAssert.cpp', './fbcode/folly/logging/AsyncFileWriter.cpp', './fbcode/folly/logging/AsyncLogWriter.cpp', './fbcode/folly/logging/CustomLogFormatter.cpp', './fbcode/folly/logging/FileWriterFactory.cpp', './fbcode/folly/logging/GlogStyleFormatter.cpp', './fbcode/folly/logging/ImmediateFileWriter.cpp', './fbcode/folly/logging/Init.cpp', './fbcode/folly/logging/InitWeak.cpp', './fbcode/folly/logging/LogCategory.cpp', './fbcode/folly/logging/LogCategoryConfig.cpp', './fbcode/folly/logging/LogConfig.cpp', './fbcode/folly/logging/LogConfigParser.cpp', './fbcode/folly/logging/LogHandlerConfig.cpp', './fbcode/folly/logging/LogLevel.cpp', './fbcode/folly/logging/LogMessage.cpp', './fbcode/folly/logging/LogName.cpp', './fbcode/folly/logging/LoggerDB.cpp', './fbcode/folly/logging/RateLimiter.cpp', './fbcode/folly/logging/StandardLogHandler.cpp', './fbcode/folly/logging/StandardLogHandlerFactory.cpp', './fbcode/folly/logging/StreamHandlerFactory.cpp', './fbcode/folly/memory/MallctlHelper.cpp', './fbcode/folly/memory/ReentrantAllocator.cpp', './fbcode/folly/net/NetOps.cpp', './fbcode/folly/portability/SysMembarrier.cpp', './fbcode/folly/synchronization/AsymmetricThreadFence.cpp', './fbcode/folly/synchronization/Hazptr.cpp', './fbcode/folly/synchronization/HazptrThreadPoolExecutor.cpp', './fbcode/folly/synchronization/ParkingLot.cpp', './fbcode/folly/system/AtFork.cpp', './fbcode/folly/system/ThreadId.cpp', './fbcode/folly/system/ThreadName.cpp', './fbcode/folly/tracing/AsyncStack.cpp']
assert 'fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp' in ['./fbcode/buck2/tests/targets/rules/cxx/cpp_test_pass.cpp', './fbcode/common/base/BuildInfo-extras.cpp', './fbcode/co...pp', './fbcode/common/gtest/LightMain.cpp', './fbcode/common/init/InitState.cpp', './fbcode/common/init/Kill.cpp', ...]
```

Reviewed By: ndmitchell

Differential Revision: D40429148

fbshipit-source-id: 52cb496dcdd829598f311f6bda8e23b72d3f61ea