shared_error: Remove an impl
Summary: The impl that's being removed here can't (and doesn't need to be) directly supported on `buck2_error`. So just remove it from `SharedError`. Only used in one place

Reviewed By: wendy728

Differential Revision: D50213695

fbshipit-source-id: 753103dc96c207cd160544009a3db5c336f76025