buck2_error: Implement `std::error::Error` in derive macro
Summary:
This brings the rest of the stack together, and removes the biggest current limitation with `buck2_error`.

The new limitation is that we now need to put `#![feature(error_generic_member_access)]` into all of our crates. I tried to avoid that, but was unsuccessful

Reviewed By: stepancheg

Differential Revision: D50934109

fbshipit-source-id: 4940865936691052211e9611a9182e88a15164de