fix --out tests on Windows (#655)
Summary:

```
failures:

---- commands::build::out::tests::test_copy_symlink stdout ----
thread 'commands::build::out::tests::test_copy_symlink' panicked at app\buck2_client\src\commands\build\out.rs:484:13:
assertion `left == right` failed
  left: "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmpnnuQho\\bar"
 right: "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\.tmpnnuQho\\bar"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- commands::build::out::tests::test_copy_directory stdout ----
thread 'commands::build::out::tests::test_copy_directory' panicked at app\buck2_client\src\commands\build\out.rs:337:13:
assertion `left == right` failed
  left: "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\.tmp5Gywx9\\foo"
 right: "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\.tmp5Gywx9\\foo"
```
Problem is that symlink values are canonicalized and extended, while we compare in asserts with non-canonicalized, hence short.

Reviewed By: JakobDegen

Differential Revision: D57471762