Fixed parameters declaration in targets command (#499)
Summary:
This was triggering the following assert:

```
thread 'main' panicked at 'Command targets: Argument or group 'package_values_regex' specified in 'conflicts_with*' for 'package-values' does not exist', C:\Users\<username>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap-3.2.25\src\builder\debug_asserts.rs:237:13
```

Pull Request resolved: https://github.com/facebook/buck2/pull/499

Reviewed By: JakobDegen

Differential Revision: D51413601

Pulled By: scottcao

fbshipit-source-id: fdc661a812ee76cdcc109edadb43a0d683e1add5