Partial revert of D61555825
Summary:
T199570037 revealed that some targets were failing in buck2 due to undefined symbols.

```
Action failed: fbcode//buck2/facebook/ingress:IngressService (cfg:linux-x86_64-fbcode-platform010-clang17-no-san-opt-by-default#c3d8afb44c2e6783) (cxx_link_executable)
Remote command returned non-zero exit code 1
Remote action, reproduce with: `frecli cas download-action e7ade14b85d4fb9d7b0395dcb84c914d3b4adf0b11cd9b4cc249d7b356076a18:145`
Stdout: <empty>
Stderr:
clang: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
ld.lld: error: undefined reference due to --no-allow-shlib-undefined: facebook$rust$stats$cxxbridge1$MapOfStringToInt64$operator$sizeof
>>> referenced by buck-out/v2/gen/fbcode/c3d8afb44c2e6783/common/rust/shed/stats/facebook/__stats_facebook-bridge__/libcommon_rust_shed_stats_facebook_stats_facebook-bridge.so

ld.lld: error: undefined reference due to --no-allow-shlib-undefined: facebook$rust$stats$cxxbridge1$MapOfStringToInt64$operator$alignof
>>> referenced by buck-out/v2/gen/fbcode/c3d8afb44c2e6783/common/rust/shed/stats/facebook/__stats_facebook-bridge__/libcommon_rust_shed_stats_facebook_stats_facebook-bridge.so
```

My guess is that because these rust cxx bridges are behind another rust cxx bridge, something wonky is happening to cause them to not show up on the link line correctly.

```
IngressService (cpp_binary)
        v
ingress-rs (rust_library + cxx_bridge) <-- This pair shows up correctly on link line
        v
...
        v
configerator_client (rust_library + cxx_bridge) <-- The rust lib is missing from the link line
```

Link argsfile from broken repro: https://www.internalfb.com/intern/everpaste/?handle=GOEsNBtz6POyrwcDAEbPb4a7mhIabsIXAAAz

I'm not 100% sure atm what's the issue, so I'm going to opt for a partial revert and investigate tomorrow.

Reviewed By: zertosh

Differential Revision: D61640971

fbshipit-source-id: be39bf9d3ec21e5257a622fa2687bc32c3a9aff4