Change lock_free_hashtable AtomicValue::Raw to Pod types
Summary:
Since version 0.6.0, the `atomic` crate requires `T: bytemuck::NoUninit` for most operations on `Atomic<T>`. https://github.com/Amanieu/atomic-rs/commit/f5333f18bf88eb1cb0c514ffcf01eef9e758d29a

In `lock_free_hashtable` this translates to requiring `<_ as AtomicValue>::Raw: bytemuck::NoUninit` due to the following points:

```lang=log,counterexample
error[E0599]: the method `load` exists for reference `&atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
  --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:49:37
   |
49 |                     let ptr = entry.load(Ordering::Acquire);
   |                                     ^^^^ method cannot be called on `&atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
           which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `get_mut` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:146:49
    |
146 |             let raw = *self.entries[self.index].get_mut();
    |                                                 ^^^^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `get_mut` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:160:49
    |
160 |             let raw = *self.entries[self.index].get_mut();
    |                                                 ^^^^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `load` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:196:45
    |
196 |             let entry = self.entries[index].load(Ordering::Acquire);
    |                                             ^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `get_mut` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:212:45
    |
212 |             let entry = self.entries[index].get_mut();
    |                                             ^^^^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `get_mut` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:214:38
    |
214 |                 *self.entries[index].get_mut() = value;
    |                                      ^^^^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `load` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:242:45
    |
242 |             let entry = self.entries[index].load(Ordering::Acquire);
    |                                             ^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`

error[E0599]: the method `compare_exchange` exists for struct `atomic::Atomic<<T as AtomicValue>::Raw>`, but its trait bounds were not satisfied
   --> fbcode/buck2/shed/lock_free_hashtable/src/fixed_cap.rs:244:43
    |
244 |                 match self.entries[index].compare_exchange(
    |                       --------------------^^^^^^^^^^^^^^^^ method cannot be called on `atomic::Atomic<<T as AtomicValue>::Raw>` due to unsatisfied trait bounds
    |
    = note: the following trait bounds were not satisfied:
            `<T as AtomicValue>::Raw: bytemuck::pod::Pod`
            which is required by `<T as AtomicValue>::Raw: bytemuck::no_uninit::NoUninit`
```

Reviewed By: capickett

Differential Revision: D116162993

fbshipit-source-id: 9e779d33d074f0baf151d8f94b94406d28a589a1