Make link_flags attribute of system_cxx_toolchain work
Summary:
Currently the `link_flags` argument is unusable.

```
system_cxx_toolchain(
    name = "cxx",
    cxx_flags = ["-std=c++17"],
    link_flags = ["-lstdc++"],
    visibility = ["PUBLIC"],
)
```

```
Error running analysis for `root//demo:blobstore-include (prelude//platforms:default#524f8da68ea2a374)`

Caused by:
    0: Error running analysis for `toolchains//:cxx (prelude//platforms:default#524f8da68ea2a374) (prelude//platforms:default#524f8da68ea2a374)`
    1: Traceback (most recent call last):
         * tools/buck/prelude/toolchains/cxx.bzl:77, in <module>
             is_pdb_generated = is_pdb_generated(linker_type, ctx.attrs.link_flags),
       error: Value `["-lstdc++"]` of type `list` does not match the type annotation `["resolved_macro"]` for argument `linker_flags`
         --> tools/buck/prelude/toolchains/cxx.bzl:77:36
          |
       77 |                 is_pdb_generated = is_pdb_generated(linker_type, ctx.attrs.link_flags),
          |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Reviewed By: zertosh

Differential Revision: D45510931

fbshipit-source-id: c587e62e6541078f5d3d0be36a969ddc63d0522b