Fix aarch64 unsigned char compile error
Summary:
On aarch64, C's `char` is unsigned by default, which breaks code that assumes
signed.  This fixes by just removing the explicit signed type hint.

```
stdout:
stderr:
error[E0308]: mismatched types
   --> buck2/buck2_core/src/exit_result.rs:233:41
    |
233 |     let mut argv_ptrs: Vec<*const i8> = argv_cstrs.map(|cstr| cstr.as_ptr());
    |                        --------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
    |                        |
    |                        expected due to this
    |
    = note: expected struct `Vec<*const i8>`
               found struct `Vec<*const u8>`

error[E0308]: mismatched types
   --> buck2/buck2_core/src/exit_result.rs:238:41
    |
238 |         libc::execv(prog_cstr.as_ptr(), argv_ptrs.as_ptr());
    |                                         ^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const *const u8`
               found raw pointer `*const *const i8`

error: aborting due to 2 previous errors
```

Reviewed By: ndmitchell

Differential Revision: D38001860

fbshipit-source-id: 089516194f9f5febce9ff5e6d18c8d7a2ea8584a