buck2_error: Require `Send`, `Sync`, `'static`
Summary: `thiserror` doesn't require these bounds of its errors, but we need lots of compatibility with `buck2_error::Error` which does, and so need to add them

Reviewed By: stepancheg

Differential Revision: D51453179

fbshipit-source-id: aee97fe871b7d1195c4a07a0900562d3dcca6553