buck2/oss: use custom %TEMP% in CircleCI on Windows (#371)
Summary:
This helps to eliminate flakiness of doctests on Windows. Sometime they fail with:
```
error: couldn't create a temp dir: The system cannot find the path specified. (os error 3) at path "C:\\Users\\CIRCLE~1.PAC\\AppData\\Local\\Temp\\rustdoctest86bH8a\\rmetawkIVXG"
```

Probably something in CircleCI runner messes with default TEMP dir, causing rustc to fail with this error.

Tested on 15 reruns of CircleCI job, they all succeeded, so I'm pretty confident this helps, although not sure exactly why. Before that, at least few out of 5 were failing.

Pull Request resolved: https://github.com/facebook/buck2/pull/371

Reviewed By: ndmitchell

Differential Revision: D47917932

fbshipit-source-id: 5d857e2f947e316e61f65764bb1f70b41bf275b8