clean stale: Wait for pending materialization before cleaning untracked artifacts
Summary:
The e2e test `test_clean_stale_scheduled` is flaky with this error:
```
Caused by:
    0: Error materializing artifact at path `buck-out/v2/gen/root/6dd044292ff31ae1/declared/__declared__/__objects__/out`
    1: Error materializing files declared by action: ae991c66496eeb9463ef5f5ac6414a3a09e66333:97 retrieved 0 seconds ago with ttl = 83626 seconds
    2: Remote Execution Error on materialize_files for ReSession reSessionID-d7c5668f-275e-41ba-97ee-c247a5366755
       Error: (Error during call: [download_with_metadata] Code: INTERNAL, Group: RE_CAS_FILESYSTEM_ERROR, Message: CAS operation[download_digests] failed: Failed to close file: facebook::remote_execution::REInternalException: Failed to rename gen/root/6dd044292ff31ae1/declared/__declared__/__objects__/out.t63165 to gen/root/6dd044292ff31ae1/declared/__declared__/__objects__/out, errorno=2, message=No such file or directory. for digest f572d396fae9206628714fb2ce00f72e94f2258f:6 -- For help debugging visit https://fburl.com/wiki/re_errors?#re-cas-filesystem-error)"}}
```

The problem is that the RE client is creating temporary files in buck-out that are copied to the materialized output path (`mv out.t63165 out`).
If clean stale runs at the exact same time, it will clean these temporary files and cause materialization to fail.

In theory this could affect users but it's very unlikely to happen in practice since clean stale runs every 24 hours, offset 12 hours from daemon start up. I couldn't find any user error samples that match this pattern.

`test_clean_stale_scheduled` hits this just because it starts a build with no offset before clean stale starts.

Reviewed By: iguridi

Differential Revision: D63784835

fbshipit-source-id: 7da37d782d0f05193ad5b0501553f8230e8e62f2