buck2_error: Remove more dead code
Summary: Forgot to delete this together with `AnyError`. Never used as a bound, so clearly doesn't do anything

Reviewed By: stepancheg

Differential Revision: D50934090

fbshipit-source-id: 131d93554cbe51c2b27b37dc94e4bbfc435ba730