Ignore health check enum variant lint
Summary:
For some reason this is only causing our windows cargo jobs to fail.
```
error: large size difference between variants
   --> app\buck2_health_check\src\interface.rs:96:1
    |
 96 | / pub enum HealthCheckEvent {
 97 | |     HealthCheckContextEvent(HealthCheckContextEvent),
    | |     ------------------------------------------------ the largest variant contains at least 216 bytes
...   |
100 | |     Snapshot(HealthCheckSnapshotData),
    | |     --------------------------------- the second-largest variant contains at least 8 bytes
101 | | }
    | |_^ the entire enum is at least 216 bytes
```

Doesn't seem like it makes sense to fix this with a box since the snapshot variant is an empty placeholder, let's just ignore it.

Reviewed By: JakobDegen

Differential Revision: D86366863

fbshipit-source-id: d944754cd16fd08da00e7b7229bbadc4a4ea590d