Reuse already declared materializations
Summary:
Meta: If you patch D75746681, and then run `buck clean && buck build --prefer-local --no-remote-cache fbcode//tupperware/scheduler/smcbridge:servicekey[objects][ServiceKey.cpp.o]`, you always hit errors like:

```
Action failed: fbcode//folly:function (generate_hmap buck-headers)
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/fbcode/86830b8b74674780/generate_hmap/buck-headers' /usr/l ...<omitted>... -file buck-out/v2/gen/fbcode/folly/__function__/21de755c4d1971a4/buck-headers.hmap.cxx_hmap_argsfile (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
Traceback (most recent call last):
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/prelude/3ad451ef8fa61963/cxx/tools/__hmap_wrapper.py__/__hmap_wrapper.py__/hmap_wrapper.py", line 58, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/prelude/3ad451ef8fa61963/cxx/tools/__hmap_wrapper.py__/__hmap_wrapper.py__/hmap_wrapper.py", line 27, in main
    with open(args.mappings_file, "r") as argsfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'buck-out/v2/gen/fbcode/folly/__function__/21de755c4d1971a4/buck-headers.hmap.cxx_hmap_argsfile'
```

Looking at some materializer logs, it looks like what happens before the action is run is:
1. Declare that argsfile to the materializer
2. Request to materialize that argsfile
3. Declare that argsfile to the materializer again (now, that argsfile can be written from multiple different actions since it is __content based__).

Right now, the behaviour seems to be that if you declare something that is materialized, then we just keep the materialized one (as long as they are the same). However, if you declare something that is already declared, then we clean up the paths and re-declare it.

This appears to be an edge case where at the point that we insert a `ProcessingFuture::Cleaning` into the tree: https://www.internalfb.com/code/fbsource/[85ba5e4edfe6]/fbcode/buck2/app/buck2_execute_impl/src/materializers/deferred/command_processor.rs?lines=887, we have just started materializing, and so whatever we materialize gets clobbered by the cleanup.

It seems like the correct thing to do if we have a `Declare`, and then get another one, is to just keep the `Declare` in place? But, I don't know the materializer well, so if someone who knows it better has an opinion on a different way to do this, please let me know.

Reviewed By: scottcao

Differential Revision: D75787322

fbshipit-source-id: fcb056873f69911b36fe0e8c92ae4b140a755887