mem: Improve error messages for size assertions
Summary:
tl;dr, before:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> fbcode/buck2/app/buck2_build_api/src/materialize.rs:78:1
   |
78 | buck2_util::size_assert::words_of_async_fn_future!(materialize_artifact_group, (_, _, _, _), 25);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `[usize; 25]` (1600 bits)
   = note: target type: `{async fn body of materialize::materialize_artifact_group()}` (1664 bits)
```

After:

```
error[E0277]: Future of type `impl futures::Future<Output = std::result::Result<ArtifactGroupValues, buck2_error::Error>>` has word count 26 (208 bytes); expected 25 (200 bytes)
  --> fbcode/buck2/app/buck2_build_api/src/materialize.rs:78:1
   |
78 | buck2_util::size_assert::words_of_async_fn_future!(materialize_artifact_group, (_, _, _, _), 25);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | unsatisfied trait bound
   | required by a bound introduced by this call
   |
   = help: the trait `buck2_util::size_assert::__macro_refs::FutureHasExpectedWordSize<208, 26, 200, 25>` is not implemented for `impl futures::Future<Output = std::result::Result<ArtifactGroupValues, buck2_error::Error>>`
   = note: this error originates in the macro `$crate::size_assert::__macro_refs::assert_async_fn_future_size` which comes from the expansion of the macro `buck2_util::size_assert::words_of_async_fn_future` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This uses a bunch of somewhat standard tricks to get this assertion into the type checker and then emit fully customized errors from there. In the past this is the kind of thing that I would've felt a bit bad about for maintainability reasons, but agents make that not really a risk anymore so this is clearly a win.

___

Differential Revision: D113643360

fbshipit-source-id: 101702158cdd63eb38c57b7e2ad416897ddf3383