buck2_error: Remove `CheckErrorType`
Summary: No longer needed, now that we don't care about error types anymore. Simplifies a lot of code and removes potential bugs

Reviewed By: stepancheg

Differential Revision: D52022091

fbshipit-source-id: 898e6615aa5be87e07536a5a37707714a1635a69