buck2_error: Check fields when parsing attributes
Summary: Instead of doing this in a second parse later. This also adds the fields check to fields on enum variants, which is good

Reviewed By: wendy728

Differential Revision: D51057844

fbshipit-source-id: 9fbcd4df805fca91af270367b7d652725ff76794