Add RUSTC_BOOTSTRAP=1 to rustdoc action
Summary:
After D63564424, our fbcode toolchain now acts similarly to stable and rejects nightly / unstable flags by default.

Without this, our rustdoc actions were failing with

```
error: the option `Z` is only accepted on the nightly compiler

error: the option `generate-link-to-definition` is only accepted on the nightly compiler

help: consider switching to a nightly toolchain: `rustup default nightly`

note: selecting a toolchain with `+toolchain` arguments require a rustup proxy; see <https://rust-lang.github.io/rustup/concepts/index.html>

note: for more information about Rust's stability policy, see <https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#unstable-features>

error: 2 nightly options were parsed

```

Reviewed By: dtolnay

Differential Revision: D63649185

fbshipit-source-id: 902e4ce81fc60574022754cd0be09a6154dcd303