: oss examples: add cxx flag to fix 5.3.0 macos
Summary:
since D68130972 where we upgraded to ocaml-5.3.0, the macos examples action has been failing (e.g. https://github.com/facebook/buck2/actions/runs/12767818183/job/35586953085) on the `//ocaml/embed:fib_cpp` target
```
third-party/ocaml/opam/lib/ocaml/caml/misc.h:353:1: error: expected expression
CAMLnoret CAMLextern void caml_fatal_error (char *, ...)
```
i expect that it's [this commit](https://github.com/ocaml/ocaml/commit/62bd62eaca91039e9e9251f1f8aa67fd4aaae1d6) landed in july 2024 that's responsible - `CAMLnoret` expands into `[[no_return]]`. passing `--std=c++-17` in the clang compiler flags allows parsing to succeed.

Differential Revision: D68157197