buck2_error: Support computing error category and type
Summary: Instead of just setting a constant, let people provide a function which takes a `&self` as input and computes the category/typ to use for the error

Reviewed By: stepancheg

Differential Revision: D51060996

fbshipit-source-id: 611b22fcd3500ce47efb6695425f4aefdfb9ca78