Disregard build script sanitizer flag mismatch
Summary:
Since {D108384430}, every `can_compile` in rustix's build script are newly detected as failing to compile in TSan mode because they fail with the following error:

https://www.internalfb.com/code/fbsource/[1a8e7598a23c79d8a0a6cdd701a2861799dc6974]/third-party/rust/vendor/rustix-1.1.4/build.rs?lines=8%2C87-90%2C198%2C210-214

```lang=log,counterexample
error: mixing `-Zsanitizer` will cause an ABI mismatch in crate `rust_out`
  |
  = help: the `-Zsanitizer` flag modifies the ABI so Rust crates compiled with different values of this flag cannot be used together safely
  = note: unset `-Zsanitizer` in this crate is incompatible with `-Zsanitizer=thread` in dependency `std`
  = help: set `-Zsanitizer=thread` in this crate or unset `-Zsanitizer` in `std`
  = help: if you are sure this will not cause problems, you may use `-Cunsafe-allow-abi-mismatch=sanitizer` to silence this error
```

For rustc invocations made by build scripts this seems fine to ignore.

Differential Revision: D108549896

fbshipit-source-id: 90059fd0a21d2d1cb0435236773d9e68a8b52f44