Unpin async-compression dependency
Summary:
This dependency was pinned in {D86970288} to block an update to versions 0.4.28 or newer. But that is unneeded since the fix in {D92161437} which fixes compatibility with 0.4.37.

Having this dependency continue to be pinned to "=0.4.9" in buck2/Cargo.toml but 0.4.37 in third-party/rust breaks dependency resolution for buck2.

```lang=log,counterexample
error: failed to select a version for the requirement `async-compression = "=0.4.9"`
candidate versions found which didn't match: 0.4.37
location searched: directory source `/data/users/dtolnay/fbsource/fbcode/buck2/../../third-party/rust/vendor` (which is replacing registry `crates-io`)
required by package `remote_execution v0.1.0 (/data/users/dtolnay/fbsource/fbcode/buck2/remote_execution/oss/re_grpc)`
perhaps a crate was updated and forgotten to be re-vendored?
```

Reviewed By: shayne-fletcher, JakobDegen

Differential Revision: D92304140

fbshipit-source-id: 1c10bb5e488e15e530155df51b835ba2b8492371