Do not dump DICE on panic by default
Summary:
When panic happens outside of DICE, DICE dumps are rarely helpful.

But if panic happens in DICE, DICE dumps are even worse because DICE dump may panic too if state is corrupted.

Also seems like dice dump does not work correctly with modern DICE?

```
thread 'buck2-rt' panicked at 'Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.', buck2/dice/dice/src/impls/dice.rs:100:12
stack backtrace:
thread '<unnamed>' panicked at 'should be present', buck2/dice/dice/src/impls/core/graph/introspection.rs:75:40
```

Anyway, make DICE dump on panic opt-in.

Reviewed By: bobyangyf

Differential Revision: D45646556

fbshipit-source-id: 1b7dadd9c8951b9468955365cbed780ec02e5452