re_grpc: consider network interruptions retryable
Right now, intermittent network failures like these fail the build immediately:

```
Error: (Failed to make BatchReadBlobs request: code: 'The operation was
cancelled', message: "operation was canceled", source: tonic::transport::Error(
Transport, hyper::Error(Canceled, "connection closed")): transport error:
operation was canceled: connection closed)
```

Add `Cancelled` cause to list of retryable errors.