Fix maven urls
Summary:
buck2 is not able to handle some of `mvn:XXX` target types.
Buck2 migration is mandatory and due by June.

We're buckifying an old legacy maven service D46071993 which is to be deprecated soon and went for using maven artifacts in buck until we delete the whole service by the EOY.

```
  * fbcode/buck2/prelude/remote_file.bzl:50, in <module>
      url = _from_mvn_url(url)
  * fbcode/buck2/prelude/remote_file.bzl:27, in _from_mvn_url
      fail("Unsupported mvn URL scheme: " + url + " (" + str(count) + ")")
error: fail: Unsupported mvn URL scheme: mvn:io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.58.Final (5)
  --> fbcode/buck2/prelude/remote_file.bzl:27:9
   |
27 |         fail("Unsupported mvn URL scheme: " + url + " (" + str(count) + ")")
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```

Reviewed By: andrewjcg

Differential Revision: D45992990

fbshipit-source-id: 0542f77255f1cd155b37f50a41f18d027e9af9e3