use absolute paths with implicit module compilation
Summary:
When compiling with implicit modules we still need to provide absolute paths to the frontend. This is required to avoid incorrect search path logic with relative SDK paths that produces errors like:
```
error: cannot open file 'sdk_path/iPhoneSimulator17.4.sdk/sdk_path/iPhoneSimulator17.4.sdk/usr/lib/swift/Swift.swiftmodule/arm64-apple-ios-simulator.swiftinterface' (No such file or directory)
```

Reviewed By: drodriguez, milend

Differential Revision: D58022827

fbshipit-source-id: ea5cdad945a56a7efea57a539d4e2f65b187ba6f