Add fixup for zerocopy 0.7.12+ to work
Summary:
New versions of `zerocopy` have a new use of `env!("CARGO_PKG_VERSION")` which requires a reindeer fixup.

```
error: environment variable `CARGO_PKG_VERSION` not defined at compile time
   --> shim/third-party/rust/zerocopy-0.7.14.crate/src/lib.rs:874:58
    |
874 |     doc = concat!("[derive]: https://docs.rs/zerocopy/", env!("CARGO_PKG_VERSION"), "/zerocopy/derive.FromZeroes.html"),
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: Cargo sets build script variables at run time. Use `std::env::var("CARGO_PKG_VERSION")` instead
    = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: environment variable `CARGO_PKG_VERSION` not defined at compile time
   --> shim/third-party/rust/zerocopy-0.7.14.crate/src/lib.rs:875:67
    |
875 |     doc = concat!("[derive-analysis]: https://docs.rs/zerocopy/", env!("CARGO_PKG_VERSION"), "/zerocopy/derive.FromZeroes.html#analysis"),
    |                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: Cargo sets build script variables at run time. Use `std::env::var("CARGO_PKG_VERSION")` instead
    = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Reviewed By: zertosh

Differential Revision: D50631736

fbshipit-source-id: ad4e490e2260f3cdec2c0152666a02dc6ce42f38