buck2_error: Respect context in late formatting
Summary: Before this diff, the `get_late_format()` on `buck2_error::Error` would return an object that did not print the context. That's unlikely to be the behavior we want and it doesn't match what happens right now (ie it breaks tests on the next diff). Change that

Reviewed By: wendy728

Differential Revision: D50437694

fbshipit-source-id: d485027b19a9afa1178b348857c1c5de02f65f17