Release static_interner 0.1.3
Summary:
The latest published version of `static_interner` does not work with the latest published version of `allocative` because `static_interner` was last published just before {D105505954} and uses `allocative`'s `relative-path` feature, while `allocative` was last published after that diff, which deleted the `relative-path` feature.

```toml
[dependencies]
allocative = "=0.3.6"
static_interner = { version = "=0.1.2", features = ["allocative"] }
```

```lang=log,counterexample
error: failed to select a version for `allocative`.
    ... required by package `static_interner v0.1.2`
    ... which satisfies dependency `static_interner = "=0.1.2"` of package `repro v0.0.0`
versions that meet the requirements `^0.3.1` are: 0.3.6, 0.3.4, 0.3.3, 0.3.2, 0.3.1

package `static_interner` depends on `allocative` with feature `relative-path` but `allocative` does not have that feature.
help: there is a feature `relative-path` with a similar name

all possible versions conflict with previously selected packages

  previously selected package `allocative v0.3.6`
    ... which satisfies dependency `allocative = "=0.3.6"` of package `repro v0.0.0`

failed to select a version for `allocative` which could resolve this conflict
```

Relevant for `pagable`, which uses `static_interner` with the `allocative` feature.

https://www.internalfb.com/code/fbsource/[a47b8b722654767985919b750818bf9acda0c671]/fbcode/buck2/pagable/Cargo.toml?lines=9%2C34

https://www.internalfb.com/code/fbsource/[a47b8b722654767985919b750818bf9acda0c671]/fbcode/buck2/Cargo.toml?lines=146%2C386

Reviewed By: ndmitchell

Differential Revision: D107206359

fbshipit-source-id: 0f2c45990de79710503b3d46fb6c60c294042c95