buck2_error: Use `try_map`
Summary: This exists and I'm just incapable of reading docs. There's still another place that needs to be fixed but this doesn't quite work there

Reviewed By: wendy728

Differential Revision: D51222312

fbshipit-source-id: 0153b57e2201a00c0c107804d99e738f519d7a78