buck2_error: Change an import
Summary: This version breaks the open source shimming. Not sure why it doesn't show up until the next diff

Reviewed By: wendy728

Differential Revision: D50168451

fbshipit-source-id: c497b19aa09796d9214ade128c1fb4974d5b5ff2