rust-project should propagate CARGO_MANIFEST_DIR
Summary:
Some proc macros require the CARGO_MANIFEST_DIR environment variable to be set. Pass this environment variable from buck to rust-analyzer, as an absolute path (see discussion in D45518093).

Previously we'd get errors from the proc macro server of the form:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', third-party/rust/vendor/schemafy-0.5.1/src/lib.rs:112:76
stack backtrace:
   0: rust_begin_unwind
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/library/core/src/result.rs:1651:5
   3: <core::result::Result<alloc::string::String, std::env::VarError>>::unwrap
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/core/src/result.rs:1076:23
   4: <schemafy::GenerateBuilder>::build_tokens
             at ./third-party/rust/vendor/schemafy-0.5.1/src/lib.rs:112:40
   5: schemafy::schemafy
             at ./third-party/rust/vendor/schemafy-0.5.1/src/lib.rs:158:5
   6: <schemafy::schemafy as core::ops::function::Fn<(proc_macro::TokenStream,)>>::call
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/core/src/ops/function.rs:79:5
   7: <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1::<schemafy::schemafy>::{closure#0}::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:435:44
   8: proc_macro::bridge::client::run_client::<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:399:30
   9: <proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::set::<(), proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/scoped_cell.rs:79:33
  10: <proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::replace::<(), <proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::set<(), proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>::{closure#0}>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/scoped_cell.rs:74:9
  11: <proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>::set::<(), proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/scoped_cell.rs:79:9
  12: proc_macro::bridge::client::run_client::<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:398:19
  13: <std::thread::local::LocalKey<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>>::try_with::<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}, ()>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/std/src/thread/local.rs:270:16
  14: <std::thread::local::LocalKey<proc_macro::bridge::scoped_cell::ScopedCell<proc_macro::bridge::client::BridgeStateL>>>::with::<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}, ()>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/std/src/thread/local.rs:246:9
  15: proc_macro::bridge::client::run_client::<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:397:22
  16: <core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/core/src/panic/unwind_safe.rs:271:9
  17: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}>, ()>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/std/src/panicking.rs:500:40
  18: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}>>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/std/src/panicking.rs:464:19
  19: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<proc_macro::bridge::client::run_client<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>::{closure#0}>, ()>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/std/src/panic.rs:142:14
  20: proc_macro::bridge::client::run_client::<proc_macro::bridge::client::TokenStream, core::option::Option<proc_macro::bridge::client::TokenStream>, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}::{closure#0}>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:384:5
  21: <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1::<schemafy::schemafy>::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/client.rs:435:17
  22: proc_macro::bridge::selfless_reify::reify_to_extern_c_fn_hrt_bridge::wrapper::<proc_macro::bridge::buffer::Buffer, <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::expand1<schemafy::schemafy>::{closure#0}>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/selfless_reify.rs:64:17
  23: <proc_macro::bridge::server::SameThread as proc_macro::bridge::server::ExecutionStrategy>::run_bridge_and_client::<proc_macro::bridge::server::Dispatcher<proc_macro::bridge::server::MarkedTypes<proc_macro_srv::abis::abi_sysroot::ra_server::RustAnalyzer>>>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/server.rs:228:9
  24: proc_macro::bridge::server::run_server::<proc_macro_srv::abis::abi_sysroot::ra_server::RustAnalyzer, proc_macro::bridge::Marked<proc_macro_srv::abis::abi_sysroot::ra_server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>, core::option::Option<proc_macro::bridge::Marked<proc_macro_srv::abis::abi_sysroot::ra_server::token_stream::TokenStream, proc_macro::bridge::client::TokenStream>>, proc_macro::bridge::server::SameThread>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/server.rs:315:11
  25: <proc_macro::bridge::client::Client<proc_macro::TokenStream, proc_macro::TokenStream>>::run::<proc_macro_srv::abis::abi_sysroot::ra_server::RustAnalyzer, proc_macro::bridge::server::SameThread>
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/build-platform010/build/rustc-beta-src/library/proc_macro/src/bridge/server.rs:333:9
  26: <proc_macro_srv::abis::abi_sysroot::Abi>::expand
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/src/tools/rust-analyzer/crates/proc-macro-srv/src/abis/abi_sysroot/mod.rs:61:31
  27: <proc_macro_srv::abis::Abi>::expand
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/src/tools/rust-analyzer/crates/proc-macro-srv/src/abis/mod.rs:128:38
  28: <proc_macro_srv::dylib::Expander>::expand
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/src/tools/rust-analyzer/crates/proc-macro-srv/src/dylib.rs:156:22
  29: <proc_macro_srv::ProcMacroSrv>::expand::{closure#2}::{closure#0}
             at /home/engshare/third-party2/rust/1.71.0+beta.3/src/rustc-beta-src//////////rustc-beta-src/src/tools/rust-analyzer/crates/proc-macro-srv/src/lib.rs:78:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Reviewed By: dtolnay

Differential Revision: D48805984

fbshipit-source-id: 42f6a4f30e8998d3d949d3b36971d4cba48d14eb