buck2/oss: use custom %TEMP% in CircleCI on Windows (#371)
Summary:
This helps to eliminate flakiness of doctests on Windows. Sometime they fail with:
```
error: couldn't create a temp dir: The system cannot find the path specified. (os error 3) at path "C:\\Users\\CIRCLE~1.PAC\\AppData\\Local\\Temp\\rustdoctest86bH8a\\rmetawkIVXG"
```

Probably something in CircleCI runner messes with default TEMP dir, causing rustc to fail with this error.

Tested on 15 reruns of CircleCI job, they all succeeded, so I'm pretty confident this helps, although not sure exactly why.

Pull Request resolved: https://github.com/facebook/buck2/pull/371

Differential Revision: D47917932

fbshipit-source-id: 0baf1d0fd5dce9520d381e3b268716af30ec0d81