buck2_error: Ban `typ = ` with `#[source]`
Summary: The next few diffs will make `#[buck2(user)]` work correctly with `#[from]` and `#[source]`. However, because `typ = ` is only allowed on the error root, it does not make sense to have it with a `#[from]` or `#[source]` field. So emit an error if someone tries to do that

Reviewed By: wendy728

Differential Revision: D51057839

fbshipit-source-id: 793bda818b5b6e859fad3f996251119cb89fee64