Delete attic from workspace members
Summary:
The **buck2-unsorted-linux** job has been failing since {D74535983} with this error.

```lang=text,counterexample
error: failed to load manifest for workspace member `/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/attic/uniplate`
referenced by workspace at `/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/Cargo.toml`

Caused by:
  failed to read `/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/fbcode/buck2/attic/uniplate/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

Reviewed By: JakobDegen

Differential Revision: D74551669

fbshipit-source-id: 19e508f89a1df0bc48cafb47755ee58df6c06169