Force legacy string concat bytecode for Android with source > 8
Summary:
Context: I want to update all tests to Mockito 5 which requires source=11 Java bytecode for test sources.

With source >= 9, javac generates different bytecode for string concatenation, using `java.lang.invoke.StringConcatFactory`.

This class exists in `core-for-system-modules.jar` in Android sdk 36 but not prior to that. A lot of our targets still build with older SDKs where this is not available, and trying to use `source = "11"` will give a compile error:
```
Failed to execute isolated step <javac>
Fatal error: Unable to find method makeConcatWithConstants

<redacted filename> error: cannot find symbol
                + "\"");
                  ^
  symbol:   method makeConcatWithConstants(java.lang.invoke.MethodHandles.Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String)
  location: interface java.lang.invoke.StringConcatFactory
```

Based on my research, the most reasonable workaround to this problem is to mimic what Android Gradle Plugin does - pass a special flag to `javac` to force legacy string concat bytecode.

References:
https://issuetracker.google.com/issues/250197571#comment19
https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaCompileUtils.kt;l=97?q=XDstringConcat%3Dinline&start=11

Reviewed By: NavidQar

Differential Revision: D85156865

fbshipit-source-id: 8a637002cc7aca06bc917dedf0035750b4209fc3