fixup for log
Resolves the error
```
error[E0425]: cannot find function `set_boxed_logger` in crate `log`
   --> third-party/rust/vendor/tracing-log-0.1.3/src/log_tracer.rs:292:14
    |
292 |         log::set_boxed_logger(logger)?;
    |              ^^^^^^^^^^^^^^^^ not found in `log`
```
caused by the `build.rs` script not running and [not
setting](https://github.com/rust-lang/log/blob/d6707108c6959ac7b60cdb60a005795ece6d82d6/build.rs#L14)
the `atomic_cas` configuration which [is
needed](https://github.com/rust-lang/log/blob/d6707108c6959ac7b60cdb60a005795ece6d82d6/src/lib.rs#L1262)
for `set_boxed_logger`.
See also [related
issue](https://github.com/tokio-rs/tracing/issues/839#issuecomment-1264204180).