Remove deps on fbsource//third-party/pypi/setuptools:setuptools
Summary:
Disable the line for now

The python test can only executed on onDemand, with following error P1800574324 so we probably need to see if it works at all on oss first.

```
[2025-05-01T11:55:51.299+01:00] ⚠ Listing failed: prelude//toolchains/android/test/com/facebook/buck/testrunner:test-entries-in-testrunner-jar
[2025-05-01T11:55:51.299+01:00] Failed to list tests. Expected exit code 0 but received: ExitStatus(unix_wait_status(1))
[2025-05-01T11:55:51.299+01:00] STDOUT:
[2025-05-01T11:55:51.299+01:00] STDERR:action_digest=66ef1226b9d220f38e4631105dfc1c515212aac132ae4a04192bdb774afbdb6c:150, re_code=FAILED_PRECONDITION, re_message=CORP network traffic does not allow use cases with a custom network isolation (fbcode_re_tests:linux-remote-execution)
```

When test executed on onDemand, without `fbsource//third-party/pypi/setuptools:setuptools` test will fail with following error.

```
    __import__(module_name, level=0)
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/prelude/0727b06621f1f00f/toolchains/android/test/com/facebook/buck/testrunner/__test-entries-in-testrunner-jar__/test-entries-in-testrunner-jar#link-tree/toolchains/android/test/com/facebook/buck/testrunner/check-allowed-entries-in-archive.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

```

Once we're sure test runner is working. I think we could add instructions to ask user do `pip install setuptools`, or IDK if there's better way we could distribute this python deps? jselbo

Reviewed By: navidqar

Differential Revision: D73993612

fbshipit-source-id: 4dd649537f80fb6643278c177a200bc86277b1cb