Fix "Could not infer crate_root"
```
$ target/release/buck2 build starlark-rust/...
When running analysis for `root//starlark-rust/starlark:starlark-bin (ovr_config//platforms:default-c7e37843b7922818)`

Caused by:
    Traceback (most recent call last):
      * prelude/rust/rust_library.bzl:149, in <module>
          artifacts = _build_library_artifacts(ctx, compile_ctx, param_lang)
      * prelude/rust/rust_library.bzl:291, in _build_library_artifacts
          link, meta = rust_compile_multi(
      * prelude/rust/build.bzl:178, in rust_compile_multi
          outs = rust_compile(
      * prelude/rust/build.bzl:214, in rust_compile
          common_args = _compute_common_args(
      * prelude/rust/build.bzl:446, in _compute_common_args
          crate_root = ctx.attrs.crate_root or _crate_root(all_srcs, crate, default_roots)
      * prelude/rust/build.bzl:581, in _crate_root
          fail("Could not infer crate_root. candidates=%s\nAdd 'crate_root = \"src/exam...
    error: fail: Could not infer crate_root. candidates=[]
    Add 'crate_root = "src/example.rs"' to your attributes to disambiguate.
       --> prelude/rust/build.bzl:581:5
        |
    581 |     fail("Could not infer crate_root. candidates=%s\nAdd 'crate_root = \"src/example.rs\"' to your attributes to disambiguate." % candidates)
        |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        |

Build ID: 9422ede9-2620-429d-ba1b-d1dcdbc8ec00
Jobs completed: 24. Time elapsed: 0.0s.
[2022-10-11T10:34:01.636+02:00] File changed: root//starlark-rust/starlark/TARGETS
[2022-10-11T10:34:01.637+02:00] File changed: root//starlark-rust/starlark
BUILD FAILED
```