De-dupe link result for extension
Summary:
This solves this error
```
BUILD FAILED
Error running analysis for fbcode//hccl:xlformers_llama4_mtia_conda (cfg:linux-x86_64-fbcode-platform010-clang17-no-san#b645abf195ce1d1f)

Caused by:
    0: Error running analysis for fbcode//hccl:wheel_env (cfg:linux-x86_64-fbcode-platform010-clang17-no-san#b645abf195ce1d1f)
    1: Error running analysis for fbcode//hccl:wheel_env (cfg:linux-x86_64-fbcode-platform010-clang17-no-san#271af8810d735456)
    2: Error running analysis for fbcode//hccl:hccl_conda.whl (cfg:linux-x86_64-fbcode-platform010-clang17-no-san#271af8810d735456)
    3: Traceback (most recent call last):
         File <builtin>, in <module>
         * fbcode/buck2/prelude/python/python_wheel.bzl:231, in _impl
             link_result = make_shared_link_result(
         * fbcode/buck2/prelude/python/python_wheel.bzl:96, in make_shared_link_result
             link_result = cxx_link_shared_library(
         * fbcode/buck2/prelude/cxx/link.bzl:547, in cxx_link_shared_library
             return cxx_link(
         * fbcode/buck2/prelude/cxx/link.bzl:496, in cxx_link
             output = ctx.actions.declare_output(output),

       error: Multiple artifacts and/or metadata files are declared at the same output location zstandard/backend_c.so declared at fbcode/buck2/prelude/cxx/link.bzl:496:18-52.
          --> fbcode/buck2/prelude/cxx/link.bzl:496:18
           |
       496 |         output = ctx.actions.declare_output(output),
           |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           |
```

Reviewed By: andrewjcg

Differential Revision: D73876612

fbshipit-source-id: 32e7769c5a1b66ee05b2bf5194ada5de55e4ceb6