fixups for tracing-subscriber
The files under `src/filter/env` where missing without the fixup.

```
Action failed: buck//third-party/rust:tracing-subscriber (rustc rlib-pic-static_pic-link/tracing_subscriber-link rlib,pic,link [diag])
Local command returned non-zero exit code 1
Reproduce locally: `/usr/bin/env "PYTHONPATH=buck-out/v2/gen/ovr_config/c7e37843b7922818/rust/tools/__rustc_action__/__r ...<omitted>... /third-party/rust/__tracing-subscriber__/rlib-pic-static_pic-link/extras/libtracing_subscriber.rlib" (rerun your previous command with -v2 to view the untruncated command)`
stdout:
stderr:
error[E0583]: file not found for module `env`
  --> third-party/rust/vendor/tracing-subscriber-0.3.16/src/filter/mod.rs:15:5
   |
15 |     mod env;
   |     ^^^^^^^^
   |
```